/*
 jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */
var process=process||{env:{NODE_ENV:"development"}};(function(z,X,oa,wa,Ja){z[wa]=z[wa]||[];z[wa].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});z=X.getElementsByTagName(oa)[0];X=X.createElement(oa);X.async=!0;X.src="https://www.googletagmanager.com/gtm.js?id="+Ja+("dataLayer"!=wa?"&l="+wa:"");z.parentNode.insertBefore(X,z)})(window,document,"script","dataLayer","GTM-M4V7BTD");process=process||{env:{NODE_ENV:"development"}};
!function(z,X){"object"==typeof module&&"object"==typeof module.exports?module.exports=z.document?X(z,!0):function(oa){if(!oa.document)throw Error("jQuery requires a window with a document");return X(oa)}:X(z)}("undefined"!=typeof window?window:this,function(z,X){function oa(a,b){b=b||N;var c=b.createElement("script");c.text=a;b.head.appendChild(c).parentNode.removeChild(c)}function wa(a){var b=!!a&&"length"in a&&a.length,c=d.type(a);return"function"!==c&&!d.isWindow(a)&&("array"===c||0===b||"number"==
typeof b&&0<b&&b-1 in a)}function Ja(a,b,c){return d.isFunction(b)?d.grep(a,function(e,f){return!!b.call(e,f,e)!==c}):b.nodeType?d.grep(a,function(e){return e===b!==c}):"string"!=typeof b?d.grep(a,function(e){return-1<Za.call(b,e)!==c}):Cc.test(b)?d.filter(b,a,c):(b=d.filter(b,a),d.grep(a,function(e){return-1<Za.call(b,e)!==c&&1===e.nodeType}))}function Ib(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function Dc(a){var b={};return d.each(a.match(sa)||[],function(c,e){b[e]=!0}),b}function Sa(a){return a}
function hb(a){throw a;}function Jb(a,b,c){var e;try{a&&d.isFunction(e=a.promise)?e.call(a).done(b).fail(c):a&&d.isFunction(e=a.then)?e.call(a,b,c):b.call(void 0,a)}catch(f){c.call(void 0,f)}}function ib(){N.removeEventListener("DOMContentLoaded",ib);z.removeEventListener("load",ib);d.ready()}function $a(){this.expando=d.expando+$a.uid++}function Kb(a,b,c){var e;if(void 0===c&&1===a.nodeType)if(e="data-"+b.replace(Ec,"-$&").toLowerCase(),c=a.getAttribute(e),"string"==typeof c){try{e=c,c="true"===
e||"false"!==e&&("null"===e?null:e===+e+""?+e:Fc.test(e)?JSON.parse(e):e)}catch(f){}pa.set(a,b,c)}else c=void 0;return c}function Lb(a,b,c,e){var f,g=1,k=20,m=e?function(){return e.cur()}:function(){return d.css(a,b,"")},q=m(),u=c&&c[3]||(d.cssNumber[b]?"":"px"),p=(d.cssNumber[b]||"px"!==u&&+q)&&ab.exec(d.css(a,b));if(p&&p[3]!==u){u=u||p[3];c=c||[];p=+q||1;do g=g||".5",p/=g,d.style(a,b,p+u);while(g!==(g=m()/q)&&1!==g&&--k)}return c&&(p=+p||+q||0,f=c[1]?p+(c[1]+1)*c[2]:+c[2],e&&(e.unit=u,e.start=p,
e.end=f)),f}function Ta(a,b){for(var c,e,f=[],g=0,k=a.length;g<k;g++)if(e=a[g],e.style)if(c=e.style.display,b){if("none"===c&&(f[g]=G.get(e,"display")||null,f[g]||(e.style.display="")),""===e.style.display&&jb(e)){c=g;var m=void 0;var q=e.ownerDocument;e=e.nodeName;var u=Mb[e];q=u?u:(m=q.body.appendChild(q.createElement(e)),u=d.css(m,"display"),m.parentNode.removeChild(m),"none"===u&&(u="block"),Mb[e]=u,u);f[c]=q}}else"none"!==c&&(f[g]="none",G.set(e,"display",c));for(g=0;g<k;g++)null!=f[g]&&(a[g].style.display=
f[g]);return a}function qa(a,b){var c;return c="undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!=typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[],void 0===b||b&&d.nodeName(a,b)?d.merge([a],c):c}function ub(a,b){for(var c=0,e=a.length;c<e;c++)G.set(a[c],"globalEval",!b||G.get(b[c],"globalEval"))}function Nb(a,b,c,e,f){for(var g,k,m,q,u=b.createDocumentFragment(),p=[],x=0,C=a.length;x<C;x++)if(g=a[x],g||0===g)if("object"===d.type(g))d.merge(p,g.nodeType?[g]:
g);else if(Gc.test(g)){k=k||u.appendChild(b.createElement("div"));m=(Ob.exec(g)||["",""])[1].toLowerCase();m=ta[m]||ta._default;k.innerHTML=m[1]+d.htmlPrefilter(g)+m[2];for(m=m[0];m--;)k=k.lastChild;d.merge(p,k.childNodes);k=u.firstChild;k.textContent=""}else p.push(b.createTextNode(g));u.textContent="";for(x=0;g=p[x++];)if(e&&-1<d.inArray(g,e))f&&f.push(g);else if(q=d.contains(g.ownerDocument,g),k=qa(u.appendChild(g),"script"),q&&ub(k),c)for(m=0;g=k[m++];)Pb.test(g.type||"")&&c.push(g);return u}
function kb(){return!0}function Ua(){return!1}function Qb(){try{return N.activeElement}catch(a){}}function vb(a,b,c,e,f,g){var k,m;if("object"==typeof b){"string"!=typeof c&&(e=e||c,c=void 0);for(m in b)vb(a,m,c,e,b[m],g);return a}if(null==e&&null==f?(f=c,e=c=void 0):null==f&&("string"==typeof c?(f=e,e=void 0):(f=e,e=c,c=void 0)),!1===f)f=Ua;else if(!f)return a;return 1===g&&(k=f,f=function(q){return d().off(q),k.apply(this,arguments)},f.guid=k.guid||(k.guid=d.guid++)),a.each(function(){d.event.add(this,
b,f,e,c)})}function Rb(a,b){return d.nodeName(a,"table")&&d.nodeName(11!==b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a:a}function Hc(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function Ic(a){var b=Jc.exec(a.type);return b?a.type=b[1]:a.removeAttribute("type"),a}function Sb(a,b){var c,e,f,g,k,m;if(1===b.nodeType){if(G.hasData(a)&&(c=G.access(a),e=G.set(b,c),m=c.events))for(f in delete e.handle,e.events={},m)for(c=0,e=m[f].length;c<e;c++)d.event.add(b,f,m[f][c]);
pa.hasData(a)&&(g=pa.access(a),k=d.extend({},g),pa.set(b,k))}}function Va(a,b,c,e){b=Tb.apply([],b);var f,g,k,m=0,q=a.length,u=q-1,p=b[0],x=d.isFunction(p);if(x||1<q&&"string"==typeof p&&!V.checkClone&&Kc.test(p))return a.each(function(J){var A=a.eq(J);x&&(b[0]=p.call(this,J,A.html()));Va(A,b,c,e)});if(q&&(f=Nb(b,a[0].ownerDocument,!1,a,e),g=f.firstChild,1===f.childNodes.length&&(f=g),g||e)){g=d.map(qa(f,"script"),Hc);for(k=g.length;m<q;m++){var C=f;m!==u&&(C=d.clone(C,!0,!0),k&&d.merge(g,qa(C,"script")));
c.call(a[m],C,m)}if(k)for(f=g[g.length-1].ownerDocument,d.map(g,Ic),m=0;m<k;m++)C=g[m],Pb.test(C.type||"")&&!G.access(C,"globalEval")&&d.contains(f,C)&&(C.src?d._evalUrl&&d._evalUrl(C.src):oa(C.textContent.replace(Lc,""),f))}return a}function Ub(a,b,c){for(var e=b?d.filter(b,a):a,f=0;null!=(b=e[f]);f++)c||1!==b.nodeType||d.cleanData(qa(b)),b.parentNode&&(c&&d.contains(b.ownerDocument,b)&&ub(qa(b,"script")),b.parentNode.removeChild(b));return a}function bb(a,b,c){var e,f,g,k,m=a.style;return c=c||
lb(a),c&&(k=c.getPropertyValue(b)||c[b],""!==k||d.contains(a.ownerDocument,a)||(k=d.style(a,b)),!V.pixelMarginRight()&&wb.test(k)&&Vb.test(b)&&(e=m.width,f=m.minWidth,g=m.maxWidth,m.minWidth=m.maxWidth=m.width=k,k=c.width,m.width=e,m.minWidth=f,m.maxWidth=g)),void 0!==k?k+"":k}function Wb(a,b){return{get:function(){return a()?void delete this.get:(this.get=b).apply(this,arguments)}}}function Xb(a){if(a in Yb)return a;for(var b=a[0].toUpperCase()+a.slice(1),c=Zb.length;c--;)if(a=Zb[c]+b,a in Yb)return a}
function $b(a,b,c){return(a=ab.exec(b))?Math.max(0,a[2]-(c||0))+(a[3]||"px"):b}function ac(a,b,c,e,f){var g=0;for(b=c===(e?"border":"content")?4:"width"===b?1:0;4>b;b+=2)"margin"===c&&(g+=d.css(a,c+Ka[b],!0,f)),e?("content"===c&&(g-=d.css(a,"padding"+Ka[b],!0,f)),"margin"!==c&&(g-=d.css(a,"border"+Ka[b]+"Width",!0,f))):(g+=d.css(a,"padding"+Ka[b],!0,f),"padding"!==c&&(g+=d.css(a,"border"+Ka[b]+"Width",!0,f)));return g}function bc(a,b,c){var e,f=!0,g=lb(a),k="border-box"===d.css(a,"boxSizing",!1,g);
if(a.getClientRects().length&&(e=a.getBoundingClientRect()[b]),0>=e||null==e){if(e=bb(a,b,g),(0>e||null==e)&&(e=a.style[b]),wb.test(e))return e;f=k&&(V.boxSizingReliable()||e===a.style[b]);e=parseFloat(e)||0}return e+ac(a,b,c||(k?"border":"content"),f,g)+"px"}function ra(a,b,c,e,f){return new ra.prototype.init(a,b,c,e,f)}function cc(){Wa&&(z.requestAnimationFrame(cc),d.fx.tick())}function dc(){return z.setTimeout(function(){Xa=void 0}),Xa=d.now()}function mb(a,b){var c=0,e={height:a};for(b=b?1:0;4>
c;c+=2-b){var f=Ka[c];e["margin"+f]=e["padding"+f]=a}return b&&(e.opacity=e.width=a),e}function ec(a,b,c){for(var e,f=(xa.tweeners[b]||[]).concat(xa.tweeners["*"]),g=0,k=f.length;g<k;g++)if(e=f[g].call(c,b,a))return e}function Mc(a,b){var c,e,f,g,k;for(c in a)if(e=d.camelCase(c),f=b[e],g=a[c],d.isArray(g)&&(f=g[1],g=a[c]=g[0]),c!==e&&(a[e]=g,delete a[c]),k=d.cssHooks[e],k&&"expand"in k)for(c in g=k.expand(g),delete a[e],g)c in a||(a[c]=g[c],b[c]=f);else b[e]=f}function xa(a,b,c){var e,f=0,g=xa.prefilters.length,
k=d.Deferred().always(function(){delete m.elem}),m=function(){if(e)return!1;var u=Xa||dc();u=Math.max(0,q.startTime+q.duration-u);for(var p=1-(u/q.duration||0),x=0,C=q.tweens.length;x<C;x++)q.tweens[x].run(p);return k.notifyWith(a,[q,p,u]),1>p&&C?u:(k.resolveWith(a,[q]),!1)},q=k.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:Xa||dc(),duration:c.duration,tweens:[],createTween:function(u,p){u=d.Tween(a,
q.opts,u,p,q.opts.specialEasing[u]||q.opts.easing);return q.tweens.push(u),u},stop:function(u){var p=0,x=u?q.tweens.length:0;if(e)return this;for(e=!0;p<x;p++)q.tweens[p].run(1);return u?(k.notifyWith(a,[q,1,0]),k.resolveWith(a,[q,u])):k.rejectWith(a,[q,u]),this}});c=q.props;for(Mc(c,q.opts.specialEasing);f<g;f++)if(b=xa.prefilters[f].call(q,a,c,q.opts))return d.isFunction(b.stop)&&(d._queueHooks(q.elem,q.opts.queue).stop=d.proxy(b.stop,b)),b;return d.map(c,ec,q),d.isFunction(q.opts.start)&&q.opts.start.call(a,
q),d.fx.timer(d.extend(m,{elem:a,anim:q,queue:q.opts.queue})),q.progress(q.opts.progress).done(q.opts.done,q.opts.complete).fail(q.opts.fail).always(q.opts.always)}function La(a){return(a.match(sa)||[]).join(" ")}function Ma(a){return a.getAttribute&&a.getAttribute("class")||""}function xb(a,b,c,e){var f;if(d.isArray(b))d.each(b,function(g,k){c||Nc.test(a)?e(a,k):xb(a+"["+("object"==typeof k&&null!=k?g:"")+"]",k,c,e)});else if(c||"object"!==d.type(b))e(a,b);else for(f in b)xb(a+"["+f+"]",b[f],c,e)}
function fc(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");var e=0,f=b.toLowerCase().match(sa)||[];if(d.isFunction(c))for(;b=f[e++];)"+"===b[0]?(b=b.slice(1)||"*",(a[b]=a[b]||[]).unshift(c)):(a[b]=a[b]||[]).push(c)}}function gc(a,b,c,e){function f(m){var q;return g[m]=!0,d.each(a[m]||[],function(u,p){u=p(b,c,e);return"string"!=typeof u||k||g[u]?k?!(q=u):void 0:(b.dataTypes.unshift(u),f(u),!1)}),q}var g={},k=a===yb;return f(b.dataTypes[0])||!g["*"]&&f("*")}function zb(a,b){var c,e,f=d.ajaxSettings.flatOptions||
{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);return e&&d.extend(!0,a,e),a}function hc(a){return d.isWindow(a)?a:9===a.nodeType&&a.defaultView}var Na=[],N=z.document,Oc=Object.getPrototypeOf,Oa=Na.slice,Tb=Na.concat,Ab=Na.push,Za=Na.indexOf,nb={},ic=nb.toString,ob=nb.hasOwnProperty,jc=ob.toString,Pc=jc.call(Object),V={},d=function(a,b){return new d.fn.init(a,b)},Qc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,Rc=/^-ms-/,Sc=/-([a-z])/g,Tc=function(a,b){return b.toUpperCase()};d.fn=d.prototype=
{jquery:"3.1.1",constructor:d,length:0,toArray:function(){return Oa.call(this)},get:function(a){return null==a?Oa.call(this):0>a?this[a+this.length]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);return a.prevObject=this,a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(Oa.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:Ab,sort:Na.sort,splice:Na.splice};d.extend=d.fn.extend=function(){var a,b,c,e,f=arguments[0]||{},g=1,k=arguments.length,m=!1;"boolean"==typeof f&&(m=f,f=arguments[g]||{},g++);"object"==typeof f||d.isFunction(f)||(f={});for(g===k&&(f=this,g--);g<k;g++)if(null!=(a=arguments[g]))for(b in a){var q=f[b];var u=a[b];f!==u&&(m&&u&&(d.isPlainObject(u)||
(c=d.isArray(u)))?(c?(c=!1,e=q&&d.isArray(q)?q:[]):e=q&&d.isPlainObject(q)?q:{},f[b]=d.extend(m,e,u)):void 0!==u&&(f[b]=u))}return f};d.extend({expando:"jQuery"+("3.1.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isFunction:function(a){return"function"===d.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){var b=d.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))},isPlainObject:function(a){var b,
c;return!(!a||"[object Object]"!==ic.call(a))&&(!(b=Oc(a))||(c=ob.call(b,"constructor")&&b.constructor,"function"==typeof c&&jc.call(c)===Pc))},isEmptyObject:function(a){for(var b in a)return!1;return!0},type:function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?nb[ic.call(a)]||"object":typeof a},globalEval:function(a){oa(a)},camelCase:function(a){return a.replace(Rc,"ms-").replace(Sc,Tc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,
b){var c,e=0;if(wa(a))for(c=a.length;e<c&&!1!==b.call(a[e],e,a[e]);e++);else for(e in a)if(!1===b.call(a[e],e,a[e]))break;return a},trim:function(a){return null==a?"":(a+"").replace(Qc,"")},makeArray:function(a,b){b=b||[];return null!=a&&(wa(Object(a))?d.merge(b,"string"==typeof a?[a]:a):Ab.call(b,a)),b},inArray:function(a,b,c){return null==b?-1:Za.call(b,a,c)},merge:function(a,b){for(var c=+b.length,e=0,f=a.length;e<c;e++)a[f++]=b[e];return a.length=f,a},grep:function(a,b,c){for(var e=[],f=0,g=a.length,
k=!c;f<g;f++)c=!b(a[f],f),c!==k&&e.push(a[f]);return e},map:function(a,b,c){var e,f=0,g=[];if(wa(a))for(e=a.length;f<e;f++){var k=b(a[f],f,c);null!=k&&g.push(k)}else for(f in a)k=b(a[f],f,c),null!=k&&g.push(k);return Tb.apply([],g)},guid:1,proxy:function(a,b){var c,e,f;if("string"==typeof b&&(c=a[b],b=a,a=c),d.isFunction(a))return e=Oa.call(arguments,2),f=function(){return a.apply(b||this,e.concat(Oa.call(arguments)))},f.guid=a.guid=a.guid||d.guid++,f},now:Date.now,support:V});"function"==typeof Symbol&&
(d.fn[Symbol.iterator]=Na[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){nb["[object "+b+"]"]=b.toLowerCase()});var Ra=function(a){function b(h,l,n,r){var t,v,y,B,w=l&&l.ownerDocument,E=l?l.nodeType:9;if(n=n||[],"string"!=typeof h||!h||1!==E&&9!==E&&11!==E)return n;if(!r&&((l?l.ownerDocument||l:Y)!==L&&Pa(l),l=l||L,ea)){if(11!==E&&(B=Uc.exec(h)))if(t=B[1])if(9===E){if(!(v=l.getElementById(t)))return n;if(v.id===t)return n.push(v),
n}else{if(w&&(v=w.getElementById(t))&&fa(l,v)&&v.id===t)return n.push(v),n}else{if(B[2])return Ha.apply(n,l.getElementsByTagName(h)),n;if((t=B[3])&&Z.getElementsByClassName&&l.getElementsByClassName)return Ha.apply(n,l.getElementsByClassName(t)),n}if(!(!Z.qsa||ya[h+" "]||R&&R.test(h))){if(1!==E){w=l;var F=h}else if("object"!==l.nodeName.toLowerCase()){(y=l.getAttribute("id"))?y=y.replace(kc,lc):l.setAttribute("id",y=M);v=pb(h);for(t=v.length;t--;)v[t]="#"+y+" "+J(v[t]);F=v.join(",");w=Bb.test(h)&&
x(l.parentNode)||l}if(F)try{return Ha.apply(n,w.querySelectorAll(F)),n}catch(D){}finally{y===M&&l.removeAttribute("id")}}}return K(h.replace(qb,"$1"),l,n,r)}function c(){function h(n,r){return l.push(n+" ")>O.cacheLength&&delete h[l.shift()],h[n+" "]=r}var l=[];return h}function e(h){return h[M]=!0,h}function f(h){var l=L.createElement("fieldset");try{return!!h(l)}catch(n){return!1}finally{l.parentNode&&l.parentNode.removeChild(l)}}function g(h,l){h=h.split("|");for(var n=h.length;n--;)O.attrHandle[h[n]]=
l}function k(h,l){var n=l&&h,r=n&&1===h.nodeType&&1===l.nodeType&&h.sourceIndex-l.sourceIndex;if(r)return r;if(n)for(;n=n.nextSibling;)if(n===l)return-1;return h?1:-1}function m(h){return function(l){return"input"===l.nodeName.toLowerCase()&&l.type===h}}function q(h){return function(l){var n=l.nodeName.toLowerCase();return("input"===n||"button"===n)&&l.type===h}}function u(h){return function(l){return"form"in l?l.parentNode&&!1===l.disabled?"label"in l?"label"in l.parentNode?l.parentNode.disabled===
h:l.disabled===h:l.isDisabled===h||l.isDisabled!==!h&&Vc(l)===h:l.disabled===h:"label"in l&&l.disabled===h}}function p(h){return e(function(l){return l=+l,e(function(n,r){for(var t,v=h([],n.length,l),y=v.length;y--;)n[t=v[y]]&&(n[t]=!(r[t]=n[t]))})})}function x(h){return h&&"undefined"!=typeof h.getElementsByTagName&&h}function C(){}function J(h){for(var l=0,n=h.length,r="";l<n;l++)r+=h[l].value;return r}function A(h,l,n){var r=l.dir,t=l.next,v=t||r,y=n&&"parentNode"===v,B=cb++;return l.first?function(w,
E,F){for(;w=w[r];)if(1===w.nodeType||y)return h(w,E,F);return!1}:function(w,E,F){var D,S,ba,aa=[T,B];if(F)for(;w=w[r];){if((1===w.nodeType||y)&&h(w,E,F))return!0}else for(;w=w[r];)if(1===w.nodeType||y)if(ba=w[M]||(w[M]={}),S=ba[w.uniqueID]||(ba[w.uniqueID]={}),t&&t===w.nodeName.toLowerCase())w=w[r]||w;else{if((D=S[v])&&D[0]===T&&D[1]===B)return aa[2]=D[2];if(S[v]=aa,aa[2]=h(w,E,F))return!0}return!1}}function Q(h){return 1<h.length?function(l,n,r){for(var t=h.length;t--;)if(!h[t](l,n,r))return!1;return!0}:
h[0]}function P(h,l,n,r,t){for(var v,y=[],B=0,w=h.length,E=null!=l;B<w;B++)(v=h[B])&&(n&&!n(v,r,t)||(y.push(v),E&&l.push(B)));return y}function za(h,l,n,r,t,v){return r&&!r[M]&&(r=za(r)),t&&!t[M]&&(t=za(t,v)),e(function(y,B,w,E){var F,D=[],S=[],ba=B.length,aa;if(!(aa=y)){aa=l||"*";for(var H=w.nodeType?[w]:w,Ca=[],la=0,Aa=H.length;la<Aa;la++)b(aa,H[la],Ca);aa=Ca}aa=!h||!y&&l?aa:P(aa,D,h,w,E);H=n?t||(y?h:ba||r)?[]:B:aa;if(n&&n(aa,H,w,E),r){var ia=P(H,S);r(ia,[],w,E);for(w=ia.length;w--;)(F=ia[w])&&
(H[S[w]]=!(aa[S[w]]=F))}if(y){if(t||h){if(t){ia=[];for(w=H.length;w--;)(F=H[w])&&ia.push(aa[w]=F);t(null,H=[],ia,E)}for(w=H.length;w--;)(F=H[w])&&-1<(ia=t?Qa(y,F):D[w])&&(y[ia]=!(B[ia]=F))}}else H=P(H===B?H.splice(ba,H.length):H),t?t(null,B,H,E):Ha.apply(B,H)})}function ha(h){var l,n,r=h.length,t=O.relative[h[0].type];var v=t||O.relative[" "];for(var y=t?1:0,B=A(function(F){return F===l},v,!0),w=A(function(F){return-1<Qa(l,F)},v,!0),E=[function(F,D,S){F=!t&&(S||D!==ca)||((l=D).nodeType?B(F,D,S):w(F,
D,S));return l=null,F}];y<r;y++)if(v=O.relative[h[y].type])E=[A(Q(E),v)];else{if(v=O.filter[h[y].type].apply(null,h[y].matches),v[M]){for(n=++y;n<r&&!O.relative[h[n].type];n++);return za(1<y&&Q(E),1<y&&J(h.slice(0,y-1).concat({value:" "===h[y-2].type?"*":""})).replace(qb,"$1"),v,y<n&&ha(h.slice(y,n)),n<r&&ha(h=h.slice(n)),n<r&&J(h))}E.push(v)}return Q(E)}function I(h,l){var n=0<l.length,r=0<h.length,t=function(v,y,B,w,E){var F,D,S=0,ba="0",aa=v&&[],H=[],Ca=ca,la=v||r&&O.find.TAG("*",E),Aa=T+=null==
Ca?1:Math.random()||.1,ia=la.length;for(E&&(ca=y===L||y||E);ba!==ia&&null!=(F=la[ba]);ba++){if(r&&F){var Cb=0;for(y||F.ownerDocument===L||(Pa(F),B=!ea);D=h[Cb++];)if(D(F,y||L,B)){w.push(F);break}E&&(T=Aa)}n&&((F=!D&&F)&&S--,v&&aa.push(F))}if(S+=ba,n&&ba!==S){for(Cb=0;D=l[Cb++];)D(aa,H,y,B);if(v){if(0<S)for(;ba--;)aa[ba]||H[ba]||(H[ba]=Wc.call(w));H=P(H)}Ha.apply(w,H);E&&!v&&0<H.length&&1<S+l.length&&b.uniqueSort(w)}return E&&(T=Aa,ca=Ca),aa};return n?e(t):t}var da,ma,K,ca,W,na,L,ja,ea,R,U,Ba,fa,M=
"sizzle"+1*new Date,Y=a.document,T=0,cb=0,ua=c(),ka=c(),ya=c(),va=function(h,l){return h===l&&(na=!0),0},Ia={}.hasOwnProperty,Da=[],Wc=Da.pop,Xc=Da.push,Ha=Da.push,mc=Da.slice,Qa=function(h,l){for(var n=0,r=h.length;n<r;n++)if(h[n]===l)return n;return-1},Yc=RegExp("[\\x20\\t\\r\\n\\f]+","g"),qb=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Zc=RegExp("^[\\x20\\t\\r\\n\\f]*,[\\x20\\t\\r\\n\\f]*"),$c=RegExp("^[\\x20\\t\\r\\n\\f]*([>+~]|[\\x20\\t\\r\\n\\f])[\\x20\\t\\r\\n\\f]*"),
ad=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),bd=RegExp(":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),cd=RegExp("^(?:\\\\.|[\\w-]|[^\x00-\\xa0])+$"),rb={ID:RegExp("^#((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)"),
CLASS:RegExp("^\\.((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)"),TAG:RegExp("^((?:\\\\.|[\\w-]|[^\x00-\\xa0])+|[*])"),ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},dd=/^(?:input|select|textarea|button)$/i,ed=/^h\d$/i,db=/^[^{]+\{\s*\[native \w/,Uc=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,Bb=/[+~]/,Ea=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),Fa=function(h,l,n){h="0x"+l-65536;return h!==h||n?l:0>h?String.fromCharCode(h+65536):String.fromCharCode(h>>10|55296,1023&h|56320)},kc=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,lc=function(h,l){return l?"\x00"===h?"\ufffd":h.slice(0,-1)+"\\"+h.charCodeAt(h.length-1).toString(16)+
" ":"\\"+h},nc=function(){Pa()},Vc=A(function(h){return!0===h.disabled&&("form"in h||"label"in h)},{dir:"parentNode",next:"legend"});try{Ha.apply(Da=mc.call(Y.childNodes),Y.childNodes),Da[Y.childNodes.length].nodeType}catch(h){Ha={apply:Da.length?function(l,n){Xc.apply(l,mc.call(n))}:function(l,n){for(var r=l.length,t=0;l[r++]=n[t++];);l.length=r-1}}}var Z=b.support={};var fd=b.isXML=function(h){h=h&&(h.ownerDocument||h).documentElement;return!!h&&"HTML"!==h.nodeName};var Pa=b.setDocument=function(h){var l,
n;h=h?h.ownerDocument||h:Y;return h!==L&&9===h.nodeType&&h.documentElement?(L=h,ja=L.documentElement,ea=!fd(L),Y!==L&&(n=L.defaultView)&&n.top!==n&&(n.addEventListener?n.addEventListener("unload",nc,!1):n.attachEvent&&n.attachEvent("onunload",nc)),Z.attributes=f(function(r){return r.className="i",!r.getAttribute("className")}),Z.getElementsByTagName=f(function(r){return r.appendChild(L.createComment("")),!r.getElementsByTagName("*").length}),Z.getElementsByClassName=db.test(L.getElementsByClassName),
Z.getById=f(function(r){return ja.appendChild(r).id=M,!L.getElementsByName||!L.getElementsByName(M).length}),Z.getById?(O.filter.ID=function(r){var t=r.replace(Ea,Fa);return function(v){return v.getAttribute("id")===t}},O.find.ID=function(r,t){if("undefined"!=typeof t.getElementById&&ea)return(r=t.getElementById(r))?[r]:[]}):(O.filter.ID=function(r){var t=r.replace(Ea,Fa);return function(v){return(v="undefined"!=typeof v.getAttributeNode&&v.getAttributeNode("id"))&&v.value===t}},O.find.ID=function(r,
t){if("undefined"!=typeof t.getElementById&&ea){var v,y=t.getElementById(r);if(y){if(v=y.getAttributeNode("id"),v&&v.value===r)return[y];var B=t.getElementsByName(r);for(t=0;y=B[t++];)if(v=y.getAttributeNode("id"),v&&v.value===r)return[y]}return[]}}),O.find.TAG=Z.getElementsByTagName?function(r,t){return"undefined"!=typeof t.getElementsByTagName?t.getElementsByTagName(r):Z.qsa?t.querySelectorAll(r):void 0}:function(r,t){var v=[],y=0;t=t.getElementsByTagName(r);if("*"===r){for(;r=t[y++];)1===r.nodeType&&
v.push(r);return v}return t},O.find.CLASS=Z.getElementsByClassName&&function(r,t){if("undefined"!=typeof t.getElementsByClassName&&ea)return t.getElementsByClassName(r)},U=[],R=[],(Z.qsa=db.test(L.querySelectorAll))&&(f(function(r){ja.appendChild(r).innerHTML="<a id='"+M+"'></a><select id='"+M+"-\r\\' msallowcapture=''><option selected=''></option></select>";r.querySelectorAll("[msallowcapture^='']").length&&R.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");r.querySelectorAll("[selected]").length||
R.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");r.querySelectorAll("[id~="+M+"-]").length||R.push("~=");r.querySelectorAll(":checked").length||R.push(":checked");r.querySelectorAll("a#"+M+"+*").length||R.push(".#.+[+~]")}),f(function(r){r.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";var t=L.createElement("input");t.setAttribute("type",
"hidden");r.appendChild(t).setAttribute("name","D");r.querySelectorAll("[name=d]").length&&R.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==r.querySelectorAll(":enabled").length&&R.push(":enabled",":disabled");ja.appendChild(r).disabled=!0;2!==r.querySelectorAll(":disabled").length&&R.push(":enabled",":disabled");r.querySelectorAll("*,:x");R.push(",.*:")})),(Z.matchesSelector=db.test(Ba=ja.matches||ja.webkitMatchesSelector||ja.mozMatchesSelector||ja.oMatchesSelector||ja.msMatchesSelector))&&f(function(r){Z.disconnectedMatch=
Ba.call(r,"*");Ba.call(r,"[s!='']:x");U.push("!=",":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")}),R=R.length&&new RegExp(R.join("|")),U=U.length&&new RegExp(U.join("|")),l=db.test(ja.compareDocumentPosition),
fa=l||db.test(ja.contains)?function(r,t){var v=9===r.nodeType?r.documentElement:r;t=t&&t.parentNode;return r===t||!(!t||1!==t.nodeType||!(v.contains?v.contains(t):r.compareDocumentPosition&&16&r.compareDocumentPosition(t)))}:function(r,t){if(t)for(;t=t.parentNode;)if(t===r)return!0;return!1},va=l?function(r,t){if(r===t)return na=!0,0;var v=!r.compareDocumentPosition-!t.compareDocumentPosition;return v?v:(v=(r.ownerDocument||r)===(t.ownerDocument||t)?r.compareDocumentPosition(t):1,1&v||!Z.sortDetached&&
t.compareDocumentPosition(r)===v?r===L||r.ownerDocument===Y&&fa(Y,r)?-1:t===L||t.ownerDocument===Y&&fa(Y,t)?1:W?Qa(W,r)-Qa(W,t):0:4&v?-1:1)}:function(r,t){if(r===t)return na=!0,0;var v=0,y=r.parentNode,B=t.parentNode,w=[r],E=[t];if(!y||!B)return r===L?-1:t===L?1:y?-1:B?1:W?Qa(W,r)-Qa(W,t):0;if(y===B)return k(r,t);for(;r=r.parentNode;)w.unshift(r);for(r=t;r=r.parentNode;)E.unshift(r);for(;w[v]===E[v];)v++;return v?k(w[v],E[v]):w[v]===Y?-1:E[v]===Y?1:0},L):L};b.matches=function(h,l){return b(h,null,
null,l)};b.matchesSelector=function(h,l){if((h.ownerDocument||h)!==L&&Pa(h),l=l.replace(ad,"='$1']"),!(!Z.matchesSelector||!ea||ya[l+" "]||U&&U.test(l)||R&&R.test(l)))try{var n=Ba.call(h,l);if(n||Z.disconnectedMatch||h.document&&11!==h.document.nodeType)return n}catch(r){}return 0<b(l,L,null,[h]).length};b.contains=function(h,l){return(h.ownerDocument||h)!==L&&Pa(h),fa(h,l)};b.attr=function(h,l){(h.ownerDocument||h)!==L&&Pa(h);var n=O.attrHandle[l.toLowerCase()];n=n&&Ia.call(O.attrHandle,l.toLowerCase())?
n(h,l,!ea):void 0;return void 0!==n?n:Z.attributes||!ea?h.getAttribute(l):(n=h.getAttributeNode(l))&&n.specified?n.value:null};b.escape=function(h){return(h+"").replace(kc,lc)};b.error=function(h){throw Error("Syntax error, unrecognized expression: "+h);};b.uniqueSort=function(h){var l,n=[],r=0,t=0;if(na=!Z.detectDuplicates,W=!Z.sortStable&&h.slice(0),h.sort(va),na){for(;l=h[t++];)l===h[t]&&(r=n.push(t));for(;r--;)h.splice(n[r],1)}return W=null,h};var Db=b.getText=function(h){var l,n="",r=0;if(l=
h.nodeType)if(1===l||9===l||11===l){if("string"==typeof h.textContent)return h.textContent;for(h=h.firstChild;h;h=h.nextSibling)n+=Db(h)}else{if(3===l||4===l)return h.nodeValue}else for(;l=h[r++];)n+=Db(l);return n};var O=b.selectors={cacheLength:50,createPseudo:e,match:rb,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(h){return h[1]=h[1].replace(Ea,Fa),h[3]=(h[3]||h[4]||
h[5]||"").replace(Ea,Fa),"~="===h[2]&&(h[3]=" "+h[3]+" "),h.slice(0,4)},CHILD:function(h){return h[1]=h[1].toLowerCase(),"nth"===h[1].slice(0,3)?(h[3]||b.error(h[0]),h[4]=+(h[4]?h[5]+(h[6]||1):2*("even"===h[3]||"odd"===h[3])),h[5]=+(h[7]+h[8]||"odd"===h[3])):h[3]&&b.error(h[0]),h},PSEUDO:function(h){var l,n=!h[6]&&h[2];return rb.CHILD.test(h[0])?null:(h[3]?h[2]=h[4]||h[5]||"":n&&bd.test(n)&&(l=pb(n,!0))&&(l=n.indexOf(")",n.length-l)-n.length)&&(h[0]=h[0].slice(0,l),h[2]=n.slice(0,l)),h.slice(0,3))}},
filter:{TAG:function(h){var l=h.replace(Ea,Fa).toLowerCase();return"*"===h?function(){return!0}:function(n){return n.nodeName&&n.nodeName.toLowerCase()===l}},CLASS:function(h){var l=ua[h+" "];return l||(l=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+h+"([\\x20\\t\\r\\n\\f]|$)"),ua(h,function(n){return l.test("string"==typeof n.className&&n.className||"undefined"!=typeof n.getAttribute&&n.getAttribute("class")||"")}))},ATTR:function(h,l,n){return function(r){r=b.attr(r,h);return null==r?"!="===l:!l||(r+="",
"="===l?r===n:"!="===l?r!==n:"^="===l?n&&0===r.indexOf(n):"*="===l?n&&-1<r.indexOf(n):"$="===l?n&&r.slice(-n.length)===n:"~="===l?-1<(" "+r.replace(Yc," ")+" ").indexOf(n):"|="===l&&(r===n||r.slice(0,n.length+1)===n+"-"))}},CHILD:function(h,l,n,r,t){var v="nth"!==h.slice(0,3),y="last"!==h.slice(-4),B="of-type"===l;return 1===r&&0===t?function(w){return!!w.parentNode}:function(w,E,F){var D,S;E=v!==y?"nextSibling":"previousSibling";var ba=w.parentNode,aa=B&&w.nodeName.toLowerCase();F=!F&&!B;var H=!1;
if(ba){if(v){for(;E;){for(D=w;D=D[E];)if(B?D.nodeName.toLowerCase()===aa:1===D.nodeType)return!1;var Ca=E="only"===h&&!Ca&&"nextSibling"}return!0}if(Ca=[y?ba.firstChild:ba.lastChild],y&&F){D=ba;var la=D[M]||(D[M]={});var Aa=la[D.uniqueID]||(la[D.uniqueID]={});var ia=Aa[h]||[];H=(S=ia[0]===T&&ia[1])&&ia[2];for(D=S&&ba.childNodes[S];D=++S&&D&&D[E]||(H=S=0)||Ca.pop();)if(1===D.nodeType&&++H&&D===w){Aa[h]=[T,S,H];break}}else if(F&&(D=w,la=D[M]||(D[M]={}),Aa=la[D.uniqueID]||(la[D.uniqueID]={}),ia=Aa[h]||
[],S=ia[0]===T&&ia[1],H=S),!1===H)for(;(D=++S&&D&&D[E]||(H=S=0)||Ca.pop())&&((B?D.nodeName.toLowerCase()!==aa:1!==D.nodeType)||!++H||(F&&(la=D[M]||(D[M]={}),Aa=la[D.uniqueID]||(la[D.uniqueID]={}),Aa[h]=[T,H]),D!==w)););return H-=t,H===r||0===H%r&&0<=H/r}}},PSEUDO:function(h,l){var n,r=O.pseudos[h]||O.setFilters[h.toLowerCase()]||b.error("unsupported pseudo: "+h);return r[M]?r(l):1<r.length?(n=[h,h,"",l],O.setFilters.hasOwnProperty(h.toLowerCase())?e(function(t,v){for(var y,B=r(t,l),w=B.length;w--;)y=
Qa(t,B[w]),t[y]=!(v[y]=B[w])}):function(t){return r(t,0,n)}):r}},pseudos:{not:e(function(h){var l=[],n=[],r=ma(h.replace(qb,"$1"));return r[M]?e(function(t,v,y,B){var w;y=r(t,null,B,[]);for(B=t.length;B--;)(w=y[B])&&(t[B]=!(v[B]=w))}):function(t,v,y){return l[0]=t,r(l,null,y,n),l[0]=null,!n.pop()}}),has:e(function(h){return function(l){return 0<b(h,l).length}}),contains:e(function(h){return h=h.replace(Ea,Fa),function(l){return-1<(l.textContent||l.innerText||Db(l)).indexOf(h)}}),lang:e(function(h){return cd.test(h||
"")||b.error("unsupported lang: "+h),h=h.replace(Ea,Fa).toLowerCase(),function(l){var n;do if(n=ea?l.lang:l.getAttribute("xml:lang")||l.getAttribute("lang"))return n=n.toLowerCase(),n===h||0===n.indexOf(h+"-");while((l=l.parentNode)&&1===l.nodeType);return!1}}),target:function(h){var l=a.location&&a.location.hash;return l&&l.slice(1)===h.id},root:function(h){return h===ja},focus:function(h){return h===L.activeElement&&(!L.hasFocus||L.hasFocus())&&!!(h.type||h.href||~h.tabIndex)},enabled:u(!1),disabled:u(!0),
checked:function(h){var l=h.nodeName.toLowerCase();return"input"===l&&!!h.checked||"option"===l&&!!h.selected},selected:function(h){return h.parentNode&&h.parentNode.selectedIndex,!0===h.selected},empty:function(h){for(h=h.firstChild;h;h=h.nextSibling)if(6>h.nodeType)return!1;return!0},parent:function(h){return!O.pseudos.empty(h)},header:function(h){return ed.test(h.nodeName)},input:function(h){return dd.test(h.nodeName)},button:function(h){var l=h.nodeName.toLowerCase();return"input"===l&&"button"===
h.type||"button"===l},text:function(h){var l;return"input"===h.nodeName.toLowerCase()&&"text"===h.type&&(null==(l=h.getAttribute("type"))||"text"===l.toLowerCase())},first:p(function(){return[0]}),last:p(function(h,l){return[l-1]}),eq:p(function(h,l,n){return[0>n?n+l:n]}),even:p(function(h,l){for(var n=0;n<l;n+=2)h.push(n);return h}),odd:p(function(h,l){for(var n=1;n<l;n+=2)h.push(n);return h}),lt:p(function(h,l,n){for(l=0>n?n+l:n;0<=--l;)h.push(l);return h}),gt:p(function(h,l,n){for(n=0>n?n+l:n;++n<
l;)h.push(n);return h})}};O.pseudos.nth=O.pseudos.eq;for(da in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})O.pseudos[da]=m(da);for(da in{submit:!0,reset:!0})O.pseudos[da]=q(da);C.prototype=O.filters=O.pseudos;O.setFilters=new C;var pb=b.tokenize=function(h,l){var n,r,t,v,y;if(v=ka[h+" "])return l?0:v.slice(0);v=h;var B=[];for(y=O.preFilter;v;){w&&!(n=Zc.exec(v))||(n&&(v=v.slice(n[0].length)||v),B.push(r=[]));var w=!1;(n=$c.exec(v))&&(w=n.shift(),r.push({value:w,type:n[0].replace(qb," ")}),
v=v.slice(w.length));for(t in O.filter)!(n=rb[t].exec(v))||y[t]&&!(n=y[t](n))||(w=n.shift(),r.push({value:w,type:t,matches:n}),v=v.slice(w.length));if(!w)break}return l?v.length:v?b.error(h):ka(h,B).slice(0)};return ma=b.compile=function(h,l){var n,r=[],t=[],v=ya[h+" "];if(!v){l||(l=pb(h));for(n=l.length;n--;)v=ha(l[n]),v[M]?r.push(v):t.push(v);v=ya(h,I(t,r));v.selector=h}return v},K=b.select=function(h,l,n,r){var t,v,y,B,w,E="function"==typeof h&&h,F=!r&&pb(h=E.selector||h);if(n=n||[],1===F.length){if(v=
F[0]=F[0].slice(0),2<v.length&&"ID"===(y=v[0]).type&&9===l.nodeType&&ea&&O.relative[v[1].type]){if(l=(O.find.ID(y.matches[0].replace(Ea,Fa),l)||[])[0],!l)return n;E&&(l=l.parentNode);h=h.slice(v.shift().value.length)}for(t=rb.needsContext.test(h)?0:v.length;t--&&(y=v[t],!O.relative[B=y.type]);)if((w=O.find[B])&&(r=w(y.matches[0].replace(Ea,Fa),Bb.test(v[0].type)&&x(l.parentNode)||l))){if(v.splice(t,1),h=r.length&&J(v),!h)return Ha.apply(n,r),n;break}}return(E||ma(h,F))(r,l,!ea,n,!l||Bb.test(h)&&x(l.parentNode)||
l),n},Z.sortStable=M.split("").sort(va).join("")===M,Z.detectDuplicates=!!na,Pa(),Z.sortDetached=f(function(h){return 1&h.compareDocumentPosition(L.createElement("fieldset"))}),f(function(h){return h.innerHTML="<a href='#'></a>","#"===h.firstChild.getAttribute("href")})||g("type|href|height|width",function(h,l,n){if(!n)return h.getAttribute(l,"type"===l.toLowerCase()?1:2)}),Z.attributes&&f(function(h){return h.innerHTML="<input/>",h.firstChild.setAttribute("value",""),""===h.firstChild.getAttribute("value")})||
g("value",function(h,l,n){if(!n&&"input"===h.nodeName.toLowerCase())return h.defaultValue}),f(function(h){return null==h.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(h,l,n){var r;if(!n)return!0===h[l]?l.toLowerCase():(r=h.getAttributeNode(l))&&r.specified?r.value:null}),b}(z);d.find=Ra;d.expr=Ra.selectors;d.expr[":"]=d.expr.pseudos;d.uniqueSort=d.unique=Ra.uniqueSort;d.text=Ra.getText;
d.isXMLDoc=Ra.isXML;d.contains=Ra.contains;d.escapeSelector=Ra.escape;var Ya=function(a,b,c){for(var e=[],f=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},oc=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},pc=d.expr.match.needsContext,qc=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i,Cc=/^.[^:#\[\.,]*$/;d.filter=function(a,b,c){var e=b[0];return c&&(a=":not("+a+")"),1===b.length&&1===e.nodeType?
d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(f){return 1===f.nodeType}))};d.fn.extend({find:function(a){var b,c=this.length,e=this;if("string"!=typeof a)return this.pushStack(d(a).filter(function(){for(b=0;b<c;b++)if(d.contains(e[b],this))return!0}));var f=this.pushStack([]);for(b=0;b<c;b++)d.find(a,e[b],f);return 1<c?d.uniqueSort(f):f},filter:function(a){return this.pushStack(Ja(this,a||[],!1))},not:function(a){return this.pushStack(Ja(this,a||[],!0))},is:function(a){return!!Ja(this,
"string"==typeof a&&pc.test(a)?d(a):a||[],!1).length}});var gd=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(d.fn.init=function(a,b,c){var e,f;if(!a)return this;if(c=c||hd,"string"==typeof a){if(e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:gd.exec(a),!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:N,!0)),qc.test(e[1])&&d.isPlainObject(b))for(e in b)d.isFunction(this[e])?
this[e](b[e]):this.attr(e,b[e]);return this}return f=N.getElementById(e[2]),f&&(this[0]=f,this.length=1),this}return a.nodeType?(this[0]=a,this.length=1,this):d.isFunction(a)?void 0!==c.ready?c.ready(a):a(d):d.makeArray(a,this)}).prototype=d.fn;var hd=d(N);var id=/^(?:parents|prev(?:Until|All))/,jd={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var e=0;e<c;e++)if(d.contains(this,b[e]))return!0})},closest:function(a,
b){var c,e=0,f=this.length,g=[],k="string"!=typeof a&&d(a);if(!pc.test(a))for(;e<f;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(k?-1<k.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"==typeof a?Za.call(d(a),this[0]):Za.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),
d(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return Ya(a,"parentNode")},parentsUntil:function(a,b,c){return Ya(a,"parentNode",c)},next:function(a){return Ib(a,"nextSibling")},prev:function(a){return Ib(a,"previousSibling")},nextAll:function(a){return Ya(a,"nextSibling")},prevAll:function(a){return Ya(a,"previousSibling")},nextUntil:function(a,b,c){return Ya(a,
"nextSibling",c)},prevUntil:function(a,b,c){return Ya(a,"previousSibling",c)},siblings:function(a){return oc((a.parentNode||{}).firstChild,a)},children:function(a){return oc(a.firstChild)},contents:function(a){return a.contentDocument||d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);return"Until"!==a.slice(-5)&&(e=c),e&&"string"==typeof e&&(f=d.filter(e,f)),1<this.length&&(jd[a]||d.uniqueSort(f),id.test(a)&&f.reverse()),this.pushStack(f)}});var sa=/[^\x20\t\r\n\f]+/g;
d.Callbacks=function(a){a="string"==typeof a?Dc(a):d.extend({},a);var b,c,e,f,g=[],k=[],m=-1,q=function(){f=a.once;for(e=b=!0;k.length;m=-1)for(c=k.shift();++m<g.length;)!1===g[m].apply(c[0],c[1])&&a.stopOnFalse&&(m=g.length,c=!1);a.memory||(c=!1);b=!1;f&&(g=c?[]:"")},u={add:function(){return g&&(c&&!b&&(m=g.length-1,k.push(c)),function C(x){d.each(x,function(J,A){d.isFunction(A)?a.unique&&u.has(A)||g.push(A):A&&A.length&&"string"!==d.type(A)&&C(A)})}(arguments),c&&!b&&q()),this},remove:function(){return d.each(arguments,
function(p,x){for(var C;-1<(C=d.inArray(x,g,C));)g.splice(C,1),C<=m&&m--}),this},has:function(p){return p?-1<d.inArray(p,g):0<g.length},empty:function(){return g&&(g=[]),this},disable:function(){return f=k=[],g=c="",this},disabled:function(){return!g},lock:function(){return f=k=[],c||b||(g=c=""),this},locked:function(){return!!f},fireWith:function(p,x){return f||(x=x||[],x=[p,x.slice?x.slice():x],k.push(x),b||q()),this},fire:function(){return u.fireWith(this,arguments),this},fired:function(){return!!e}};
return u};d.extend({Deferred:function(a){var b=[["notify","progress",d.Callbacks("memory"),d.Callbacks("memory"),2],["resolve","done",d.Callbacks("once memory"),d.Callbacks("once memory"),0,"resolved"],["reject","fail",d.Callbacks("once memory"),d.Callbacks("once memory"),1,"rejected"]],c="pending",e={state:function(){return c},always:function(){return f.done(arguments).fail(arguments),this},"catch":function(g){return e.then(null,g)},pipe:function(){var g=arguments;return d.Deferred(function(k){d.each(b,
function(m,q){var u=d.isFunction(g[q[4]])&&g[q[4]];f[q[1]](function(){var p=u&&u.apply(this,arguments);p&&d.isFunction(p.promise)?p.promise().progress(k.notify).done(k.resolve).fail(k.reject):k[q[0]+"With"](this,u?[p]:arguments)})});g=null}).promise()},then:function(g,k,m){function q(p,x,C,J){return function(){var A=this,Q=arguments,P=function(){var ha;if(!(p<u)){if(ha=C.apply(A,Q),ha===x.promise())throw new TypeError("Thenable self-resolution");var I=ha&&("object"==typeof ha||"function"==typeof ha)&&
ha.then;d.isFunction(I)?J?I.call(ha,q(u,x,Sa,J),q(u,x,hb,J)):(u++,I.call(ha,q(u,x,Sa,J),q(u,x,hb,J),q(u,x,Sa,x.notifyWith))):(C!==Sa&&(A=void 0,Q=[ha]),(J||x.resolveWith)(A,Q))}},za=J?P:function(){try{P()}catch(ha){d.Deferred.exceptionHook&&d.Deferred.exceptionHook(ha,za.stackTrace),p+1>=u&&(C!==hb&&(A=void 0,Q=[ha]),x.rejectWith(A,Q))}};p?za():(d.Deferred.getStackHook&&(za.stackTrace=d.Deferred.getStackHook()),z.setTimeout(za))}}var u=0;return d.Deferred(function(p){b[0][3].add(q(0,p,d.isFunction(m)?
m:Sa,p.notifyWith));b[1][3].add(q(0,p,d.isFunction(g)?g:Sa));b[2][3].add(q(0,p,d.isFunction(k)?k:hb))}).promise()},promise:function(g){return null!=g?d.extend(g,e):e}},f={};return d.each(b,function(g,k){var m=k[2],q=k[5];e[k[1]]=m.add;q&&m.add(function(){c=q},b[3-g][2].disable,b[0][2].lock);m.add(k[3].fire);f[k[0]]=function(){return f[k[0]+"With"](this===f?void 0:this,arguments),this};f[k[0]+"With"]=m.fireWith}),e.promise(f),a&&a.call(f,f),f},when:function(a){var b=arguments.length,c=b,e=Array(c),
f=Oa.call(arguments),g=d.Deferred(),k=function(m){return function(q){e[m]=this;f[m]=1<arguments.length?Oa.call(arguments):q;--b||g.resolveWith(e,f)}};if(1>=b&&(Jb(a,g.done(k(c)).resolve,g.reject),"pending"===g.state()||d.isFunction(f[c]&&f[c].then)))return g.then();for(;c--;)Jb(f[c],k(c),g.reject);return g.promise()}});var kd=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;d.Deferred.exceptionHook=function(a,b){z.console&&z.console.warn&&a&&kd.test(a.name)&&z.console.warn("jQuery.Deferred exception: "+
a.message,a.stack,b)};d.readyException=function(a){z.setTimeout(function(){throw a;})};var Eb=d.Deferred();d.fn.ready=function(a){return Eb.then(a)["catch"](function(b){d.readyException(b)}),this};d.extend({isReady:!1,readyWait:1,holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||Eb.resolveWith(N,[d]))}});d.ready.then=Eb.then;"complete"===N.readyState||"loading"!==N.readyState&&!N.documentElement.doScroll?z.setTimeout(d.ready):
(N.addEventListener("DOMContentLoaded",ib),z.addEventListener("load",ib));var Ga=function(a,b,c,e,f,g,k){var m=0,q=a.length,u=null==c;if("object"===d.type(c))for(m in f=!0,c)Ga(a,b,m,c[m],!0,g,k);else if(void 0!==e&&(f=!0,d.isFunction(e)||(k=!0),u&&(k?(b.call(a,e),b=null):(u=b,b=function(p,x,C){return u.call(d(p),C)})),b))for(;m<q;m++)b(a[m],c,k?e:e.call(a[m],m,b(a[m],c)));return f?a:u?b.call(a):q?b(a[0],c):g},sb=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};$a.uid=1;$a.prototype=
{cache:function(a){var b=a[this.expando];return b||(b={},sb(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,this.expando,{value:b,configurable:!0}))),b},set:function(a,b,c){var e;a=this.cache(a);if("string"==typeof b)a[d.camelCase(b)]=c;else for(e in b)a[d.camelCase(e)]=b[e];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][d.camelCase(b)]},access:function(a,b,c){return void 0===b||b&&"string"==typeof b&&void 0===c?this.get(a,b):(this.set(a,b,c),
void 0!==c?c:b)},remove:function(a,b){var c,e=a[this.expando];if(void 0!==e){if(void 0!==b)for(d.isArray(b)?b=b.map(d.camelCase):(b=d.camelCase(b),b=b in e?[b]:b.match(sa)||[]),c=b.length;c--;)delete e[b[c]];(void 0===b||d.isEmptyObject(e))&&(a.nodeType?a[this.expando]=void 0:delete a[this.expando])}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var G=new $a,pa=new $a,Fc=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Ec=/[A-Z]/g;d.extend({hasData:function(a){return pa.hasData(a)||
G.hasData(a)},data:function(a,b,c){return pa.access(a,b,c)},removeData:function(a,b){pa.remove(a,b)},_data:function(a,b,c){return G.access(a,b,c)},_removeData:function(a,b){G.remove(a,b)}});d.fn.extend({data:function(a,b){var c,e,f,g=this[0],k=g&&g.attributes;if(void 0===a){if(this.length&&(f=pa.get(g),1===g.nodeType&&!G.get(g,"hasDataAttrs"))){for(c=k.length;c--;)k[c]&&(e=k[c].name,0===e.indexOf("data-")&&(e=d.camelCase(e.slice(5)),Kb(g,e,f[e])));G.set(g,"hasDataAttrs",!0)}return f}return"object"==
typeof a?this.each(function(){pa.set(this,a)}):Ga(this,function(m){var q;if(g&&void 0===m){if((q=pa.get(g,a),void 0!==q)||(q=Kb(g,a),void 0!==q))return q}else this.each(function(){pa.set(this,a,m)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){pa.remove(this,a)})}});d.extend({queue:function(a,b,c){var e;if(a)return b=(b||"fx")+"queue",e=G.get(a,b),c&&(!e||d.isArray(c)?e=G.access(a,b,d.makeArray(c)):e.push(c)),e||[]},dequeue:function(a,b){b=b||"fx";var c=
d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),k=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,k,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return G.get(a,c)||G.access(a,c,{empty:d.Callbacks("once memory").add(function(){G.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),arguments.length<c?d.queue(this[0],a):void 0===
b?this:this.each(function(){var e=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==e[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,k=this.length,m=function(){--e||f.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=void 0);for(a=a||"fx";k--;)(c=G.get(g[k],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(m));return m(),f.promise(b)}});var rc=
/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,ab=new RegExp("^(?:([+-])=|)("+rc+")([a-z%]*)$","i"),Ka=["Top","Right","Bottom","Left"],jb=function(a,b){return a=b||a,"none"===a.style.display||""===a.style.display&&d.contains(a.ownerDocument,a)&&"none"===d.css(a,"display")},sc=function(a,b,c,e){var f,g={};for(f in b)g[f]=a.style[f],a.style[f]=b[f];c=c.apply(a,e||[]);for(f in b)a.style[f]=g[f];return c},Mb={};d.fn.extend({show:function(){return Ta(this,!0)},hide:function(){return Ta(this)},toggle:function(a){return"boolean"==
typeof a?a?this.show():this.hide():this.each(function(){jb(this)?d(this).show():d(this).hide()})}});var tc=/^(?:checkbox|radio)$/i,Ob=/<([a-z][^\/\0>\x20\t\r\n\f]+)/i,Pb=/^$|\/(?:java|ecma)script/i,ta={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};ta.optgroup=ta.option;ta.tbody=ta.tfoot=ta.colgroup=
ta.caption=ta.thead;ta.th=ta.td;var Gc=/<|&#?\w+;/;!function(){var a=N.createDocumentFragment().appendChild(N.createElement("div")),b=N.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);V.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";V.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue}();var tb=N.documentElement,ld=/^key/,md=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,
uc=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,e,f){var g,k,m,q,u,p,x,C;if(q=G.get(a))for(c.handler&&(g=c,c=g.handler,f=g.selector),f&&d.find.matchesSelector(tb,f),c.guid||(c.guid=d.guid++),(m=q.events)||(m=q.events={}),(k=q.handle)||(k=q.handle=function(Q){return"undefined"!=typeof d&&d.event.triggered!==Q.type?d.event.dispatch.apply(a,arguments):void 0}),b=(b||"").match(sa)||[""],q=b.length;q--;){var J=uc.exec(b[q])||[];var A=C=J[1];J=(J[2]||"").split(".").sort();A&&(p=d.event.special[A]||
{},A=(f?p.delegateType:p.bindType)||A,p=d.event.special[A]||{},u=d.extend({type:A,origType:C,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:J.join(".")},g),(x=m[A])||(x=m[A]=[],x.delegateCount=0,p.setup&&!1!==p.setup.call(a,e,J,k)||a.addEventListener&&a.addEventListener(A,k)),p.add&&(p.add.call(a,u),u.handler.guid||(u.handler.guid=c.guid)),f?x.splice(x.delegateCount++,0,u):x.push(u),d.event.global[A]=!0)}},remove:function(a,b,c,e,f){var g,k,m,q,
u,p,x,C,J=G.hasData(a)&&G.get(a);if(J&&(q=J.events)){b=(b||"").match(sa)||[""];for(u=b.length;u--;)if(m=uc.exec(b[u])||[],p=C=m[1],x=(m[2]||"").split(".").sort(),p){var A=d.event.special[p]||{};p=(e?A.delegateType:A.bindType)||p;var Q=q[p]||[];m=m[2]&&new RegExp("(^|\\.)"+x.join("\\.(?:.*\\.|)")+"(\\.|$)");for(k=g=Q.length;g--;){var P=Q[g];!f&&C!==P.origType||c&&c.guid!==P.guid||m&&!m.test(P.namespace)||e&&e!==P.selector&&("**"!==e||!P.selector)||(Q.splice(g,1),P.selector&&Q.delegateCount--,A.remove&&
A.remove.call(a,P))}k&&!Q.length&&(A.teardown&&!1!==A.teardown.call(a,x,J.handle)||d.removeEvent(a,p,J.handle),delete q[p])}else for(p in q)d.event.remove(a,p+b[u],c,e,!0);d.isEmptyObject(q)&&G.remove(a,"handle events")}},dispatch:function(a){var b=d.event.fix(a),c,e,f,g,k=Array(arguments.length);var m=(G.get(this,"events")||{})[b.type]||[];var q=d.event.special[b.type]||{};k[0]=b;for(c=1;c<arguments.length;c++)k[c]=arguments[c];if(b.delegateTarget=this,!q.preDispatch||!1!==q.preDispatch.call(this,
b)){var u=d.event.handlers.call(this,b,m);for(c=0;(f=u[c++])&&!b.isPropagationStopped();)for(b.currentTarget=f.elem,m=0;(g=f.handlers[m++])&&!b.isImmediatePropagationStopped();)b.rnamespace&&!b.rnamespace.test(g.namespace)||(b.handleObj=g,b.data=g.data,e=((d.event.special[g.origType]||{}).handle||g.handler).apply(f.elem,k),void 0!==e&&!1===(b.result=e)&&(b.preventDefault(),b.stopPropagation()));return q.postDispatch&&q.postDispatch.call(this,b),b.result}},handlers:function(a,b){var c,e=[],f=b.delegateCount,
g=a.target;if(f&&g.nodeType&&!("click"===a.type&&1<=a.button))for(;g!==this;g=g.parentNode||this)if(1===g.nodeType&&("click"!==a.type||!0!==g.disabled)){var k=[];var m={};for(c=0;c<f;c++){var q=b[c];var u=q.selector+" ";void 0===m[u]&&(m[u]=q.needsContext?-1<d(u,this).index(g):d.find(u,this,null,[g]).length);m[u]&&k.push(q)}k.length&&e.push({elem:g,handlers:k})}return g=this,f<b.length&&e.push({elem:g,handlers:b.slice(f)}),e},addProp:function(a,b){Object.defineProperty(d.Event.prototype,a,{enumerable:!0,
configurable:!0,get:d.isFunction(b)?function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(c){Object.defineProperty(this,a,{enumerable:!0,configurable:!0,writable:!0,value:c})}})},fix:function(a){return a[d.expando]?a:new d.Event(a)},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==Qb()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===Qb()&&this.blur)return this.blur(),
!1},delegateType:"focusout"},click:{trigger:function(){if("checkbox"===this.type&&this.click&&d.nodeName(this,"input"))return this.click(),!1},_default:function(a){return d.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};d.Event=function(a,b){return this instanceof d.Event?(a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=
a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?kb:Ua,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=a.relatedTarget):this.type=a,b&&d.extend(this,b),this.timeStamp=a&&a.timeStamp||d.now(),void(this[d.expando]=!0)):new d.Event(a,b)};d.Event.prototype={constructor:d.Event,isDefaultPrevented:Ua,isPropagationStopped:Ua,isImmediatePropagationStopped:Ua,isSimulated:!1,preventDefault:function(){var a=this.originalEvent;
this.isDefaultPrevented=kb;a&&!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=kb;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=kb;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};d.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,eventPhase:!0,metaKey:!0,pageX:!0,pageY:!0,shiftKey:!0,
view:!0,"char":!0,charCode:!0,key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:function(a){var b=a.button;return null==a.which&&ld.test(a.type)?null!=a.charCode?a.charCode:a.keyCode:!a.which&&void 0!==b&&md.test(a.type)?1&b?1:2&b?3:4&b?2:0:a.which}},d.event.addProp);d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},
function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(c){var e,f=c.relatedTarget,g=c.handleObj;return f&&(f===this||d.contains(this,f))||(c.type=g.origType,e=g.handler.apply(this,arguments),c.type=b),e}}});d.fn.extend({on:function(a,b,c,e){return vb(this,a,b,c,e)},one:function(a,b,c,e){return vb(this,a,b,c,e,1)},off:function(a,b,c){var e,f;if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,
e.handler),this;if("object"==typeof a){for(f in a)this.off(f,b,a[f]);return this}return!1!==b&&"function"!=typeof b||(c=b,b=void 0),!1===c&&(c=Ua),this.each(function(){d.event.remove(this,a,c,b)})}});var nd=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi,od=/<script|<style|<link/i,Kc=/checked\s*(?:[^=]|=\s*.checked.)/i,Jc=/^true\/(.*)/,Lc=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a.replace(nd,"<$1></$2>")},clone:function(a,
b,c){var e,f=a.cloneNode(!0),g=d.contains(a.ownerDocument,a);if(!(V.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){var k=qa(f);var m=qa(a);var q=0;for(e=m.length;q<e;q++){var u=m[q],p=k[q],x=p.nodeName.toLowerCase();"input"===x&&tc.test(u.type)?p.checked=u.checked:"input"!==x&&"textarea"!==x||(p.defaultValue=u.defaultValue)}}if(b)if(c)for(m=m||qa(a),k=k||qa(f),q=0,e=m.length;q<e;q++)Sb(m[q],k[q]);else Sb(a,f);return k=qa(f,"script"),0<k.length&&ub(k,!g&&qa(a,"script")),f},cleanData:function(a){for(var b,
c,e,f=d.event.special,g=0;void 0!==(c=a[g]);g++)if(sb(c)){if(b=c[G.expando]){if(b.events)for(e in b.events)f[e]?d.event.remove(c,e):d.removeEvent(c,e,b.handle);c[G.expando]=void 0}c[pa.expando]&&(c[pa.expando]=void 0)}}});d.fn.extend({detach:function(a){return Ub(this,a,!0)},remove:function(a){return Ub(this,a)},text:function(a){return Ga(this,function(b){return void 0===b?d.text(this):this.empty().each(function(){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||(this.textContent=b)})},null,
a,arguments.length)},append:function(){return Va(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||Rb(this,a).appendChild(a)})},prepend:function(){return Va(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=Rb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return Va(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return Va(this,arguments,function(a){this.parentNode&&
this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(qa(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null!=a&&a,b=null==b?a:b,this.map(function(){return d.clone(this,a,b)})},html:function(a){return Ga(this,function(b){var c=this[0]||{},e=0,f=this.length;if(void 0===b&&1===c.nodeType)return c.innerHTML;if("string"==typeof b&&!od.test(b)&&!ta[(Ob.exec(b)||["",""])[1].toLowerCase()]){b=d.htmlPrefilter(b);
try{for(;e<f;e++)c=this[e]||{},1===c.nodeType&&(d.cleanData(qa(c,!1)),c.innerHTML=b);c=0}catch(g){}}c&&this.empty().append(b)},null,a,arguments.length)},replaceWith:function(){var a=[];return Va(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(qa(this)),c&&c.replaceChild(b,this))},a)}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(c){for(var e=[],f=d(c),g=f.length-
1,k=0;k<=g;k++)c=k===g?this:this.clone(!0),d(f[k])[b](c),Ab.apply(e,c.get());return this.pushStack(e)}});var Vb=/^margin/,wb=new RegExp("^("+rc+")(?!px)[a-z%]+$","i"),lb=function(a){var b=a.ownerDocument.defaultView;return b&&b.opener||(b=z),b.getComputedStyle(a)};!function(){function a(){if(k){k.style.cssText="box-sizing:border-box;position:relative;display:block;margin:auto;border:1px;padding:1px;top:1%;width:50%";k.innerHTML="";tb.appendChild(g);var m=z.getComputedStyle(k);b="1%"!==m.top;f="2px"===
m.marginLeft;c="4px"===m.width;k.style.marginRight="50%";e="4px"===m.marginRight;tb.removeChild(g);k=null}}var b,c,e,f,g=N.createElement("div"),k=N.createElement("div");k.style&&(k.style.backgroundClip="content-box",k.cloneNode(!0).style.backgroundClip="",V.clearCloneStyle="content-box"===k.style.backgroundClip,g.style.cssText="border:0;width:8px;height:0;top:0;left:-9999px;padding:0;margin-top:1px;position:absolute",g.appendChild(k),d.extend(V,{pixelPosition:function(){return a(),b},boxSizingReliable:function(){return a(),
c},pixelMarginRight:function(){return a(),e},reliableMarginLeft:function(){return a(),f}}))}();var pd=/^(none|table(?!-c[ea]).+)/,qd={position:"absolute",visibility:"hidden",display:"block"},vc={letterSpacing:"0",fontWeight:"400"},Zb=["Webkit","Moz","ms"],Yb=N.createElement("div").style;d.extend({cssHooks:{opacity:{get:function(a,b){if(b)return a=bb(a,"opacity"),""===a?"1":a}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,
opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,k,m=d.camelCase(b),q=a.style;return b=d.cssProps[m]||(d.cssProps[m]=Xb(m)||m),k=d.cssHooks[b]||d.cssHooks[m],void 0===c?k&&"get"in k&&void 0!==(f=k.get(a,!1,e))?f:q[b]:(g=typeof c,"string"===g&&(f=ab.exec(c))&&f[1]&&(c=Lb(a,b,f),g="number"),null!=c&&c===c&&("number"===g&&(c+=f&&f[3]||(d.cssNumber[m]?"":"px")),V.clearCloneStyle||""!==
c||0!==b.indexOf("background")||(q[b]="inherit"),k&&"set"in k&&void 0===(c=k.set(a,c,e))||(q[b]=c)),void 0)}},css:function(a,b,c,e){var f,g,k,m=d.camelCase(b);return b=d.cssProps[m]||(d.cssProps[m]=Xb(m)||m),k=d.cssHooks[b]||d.cssHooks[m],k&&"get"in k&&(f=k.get(a,!0,c)),void 0===f&&(f=bb(a,b,e)),"normal"===f&&b in vc&&(f=vc[b]),""===c||c?(g=parseFloat(f),!0===c||isFinite(g)?g||0:f):f}});d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(c,e,f){if(e)return!pd.test(d.css(c,"display"))||
c.getClientRects().length&&c.getBoundingClientRect().width?bc(c,b,f):sc(c,qd,function(){return bc(c,b,f)})},set:function(c,e,f){var g,k=f&&lb(c);f=f&&ac(c,b,f,"border-box"===d.css(c,"boxSizing",!1,k),k);return f&&(g=ab.exec(e))&&"px"!==(g[3]||"px")&&(c.style[b]=e,e=d.css(c,b)),$b(c,e,f)}}});d.cssHooks.marginLeft=Wb(V.reliableMarginLeft,function(a,b){if(b)return(parseFloat(bb(a,"marginLeft"))||a.getBoundingClientRect().left-sc(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+"px"});
d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var e=0,f={};for(c="string"==typeof c?c.split(" "):[c];4>e;e++)f[a+Ka[e]+b]=c[e]||c[e-2]||c[0];return f}};Vb.test(a)||(d.cssHooks[a+b].set=$b)});d.fn.extend({css:function(a,b){return Ga(this,function(c,e,f){var g,k={},m=0;if(d.isArray(e)){f=lb(c);for(g=e.length;m<g;m++)k[e[m]]=d.css(c,e[m],!1,f);return k}return void 0!==f?d.style(c,e,f):d.css(c,e)},a,b,1<arguments.length)}});d.Tween=ra;ra.prototype={constructor:ra,
init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=ra.propHooks[this.prop];return a&&a.get?a.get(this):ra.propHooks._default.get(this)},run:function(a){var b,c=ra.propHooks[this.prop];return this.options.duration?this.pos=b=d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):this.pos=b=a,this.now=(this.end-this.start)*b+this.start,
this.options.step&&this.options.step.call(this.elem,this.now,this),c&&c.set?c.set(this):ra.propHooks._default.set(this),this}};ra.prototype.init.prototype=ra.prototype;ra.propHooks={_default:{get:function(a){var b;return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(b=d.css(a.elem,a.prop,""),b&&"auto"!==b?b:0)},set:function(a){d.fx.step[a.prop]?d.fx.step[a.prop](a):1!==a.elem.nodeType||null==a.elem.style[d.cssProps[a.prop]]&&!d.cssHooks[a.prop]?a.elem[a.prop]=
a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};ra.propHooks.scrollTop=ra.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=ra.prototype.init;d.fx.step={};var Xa,Wa,rd=/^(?:toggle|show|hide)$/,sd=/queueHooks$/;d.Animation=d.extend(xa,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);return Lb(c.elem,a,ab.exec(b),c),c}]},tweener:function(a,
b){d.isFunction(a)?(b=a,a=["*"]):a=a.match(sa);for(var c,e=0,f=a.length;e<f;e++)c=a[e],xa.tweeners[c]=xa.tweeners[c]||[],xa.tweeners[c].unshift(b)},prefilters:[function(a,b,c){var e,f,g,k,m,q,u,p,x="width"in b||"height"in b,C=this,J={},A=a.style,Q=a.nodeType&&jb(a),P=G.get(a,"fxshow");c.queue||(k=d._queueHooks(a,"fx"),null==k.unqueued&&(k.unqueued=0,m=k.empty.fire,k.empty.fire=function(){k.unqueued||m()}),k.unqueued++,C.always(function(){C.always(function(){k.unqueued--;d.queue(a,"fx").length||k.empty.fire()})}));
for(e in b)if(f=b[e],rd.test(f)){if(delete b[e],g=g||"toggle"===f,f===(Q?"hide":"show")){if("show"!==f||!P||void 0===P[e])continue;Q=!0}J[e]=P&&P[e]||d.style(a,e)}if(q=!d.isEmptyObject(b),q||!d.isEmptyObject(J))for(e in x&&1===a.nodeType&&(c.overflow=[A.overflow,A.overflowX,A.overflowY],u=P&&P.display,null==u&&(u=G.get(a,"display")),p=d.css(a,"display"),"none"===p&&(u?p=u:(Ta([a],!0),u=a.style.display||u,p=d.css(a,"display"),Ta([a]))),("inline"===p||"inline-block"===p&&null!=u)&&"none"===d.css(a,
"float")&&(q||(C.done(function(){A.display=u}),null==u&&(p=A.display,u="none"===p?"":p)),A.display="inline-block")),c.overflow&&(A.overflow="hidden",C.always(function(){A.overflow=c.overflow[0];A.overflowX=c.overflow[1];A.overflowY=c.overflow[2]})),q=!1,J)q||(P?"hidden"in P&&(Q=P.hidden):P=G.access(a,"fxshow",{display:u}),g&&(P.hidden=!Q),Q&&Ta([a],!0),C.done(function(){Q||Ta([a]);G.remove(a,"fxshow");for(e in J)d.style(a,e,J[e])})),q=ec(Q?P[e]:0,e,C),e in P||(P[e]=q.start,Q&&(q.end=q.start,q.start=
0))}],prefilter:function(a,b){b?xa.prefilters.unshift(a):xa.prefilters.push(a)}});d.speed=function(a,b,c){var e=a&&"object"==typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};return d.fx.off||N.hidden?e.duration=0:"number"!=typeof e.duration&&(e.duration in d.fx.speeds?e.duration=d.fx.speeds[e.duration]:e.duration=d.fx.speeds._default),null!=e.queue&&!0!==e.queue||(e.queue="fx"),e.old=e.complete,e.complete=function(){d.isFunction(e.old)&&
e.old.call(this);e.queue&&d.dequeue(this,e.queue)},e};d.fn.extend({fadeTo:function(a,b,c,e){return this.filter(jb).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,c,e){var f=d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var k=xa(this,d.extend({},a),g);(f||G.get(this,"finish"))&&k.stop(!0)};return b.finish=b,f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(f){var g=f.stop;delete f.stop;g(c)};return"string"!=typeof a&&(c=b,b=a,
a=void 0),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var f=!0,g=null!=a&&a+"queueHooks",k=d.timers,m=G.get(this);if(g)m[g]&&m[g].stop&&e(m[g]);else for(g in m)m[g]&&m[g].stop&&sd.test(g)&&e(m[g]);for(g=k.length;g--;)k[g].elem!==this||null!=a&&k[g].queue!==a||(k[g].anim.stop(c),f=!1,k.splice(g,1));!f&&c||d.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b=G.get(this),c=b[a+"queue"];var e=b[a+"queueHooks"];var f=d.timers,g=c?c.length:0;b.finish=!0;
d.queue(this,a,[]);e&&e.stop&&e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,1));for(e=0;e<g;e++)c[e]&&c[e].finish&&c[e].finish.call(this);delete b.finish})}});d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(e,f,g){return null==e||"boolean"==typeof e?c.apply(this,arguments):this.animate(mb(b,!0),e,f,g)}});d.each({slideDown:mb("show"),slideUp:mb("hide"),slideToggle:mb("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},
fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(c,e,f){return this.animate(b,c,e,f)}});d.timers=[];d.fx.tick=function(){var a=0,b=d.timers;for(Xa=d.now();a<b.length;a++){var c=b[a];c()||b[a]!==c||b.splice(a--,1)}b.length||d.fx.stop();Xa=void 0};d.fx.timer=function(a){d.timers.push(a);a()?d.fx.start():d.timers.pop()};d.fx.interval=13;d.fx.start=function(){Wa||(Wa=z.requestAnimationFrame?z.requestAnimationFrame(cc):z.setInterval(d.fx.tick,d.fx.interval))};d.fx.stop=function(){z.cancelAnimationFrame?
z.cancelAnimationFrame(Wa):z.clearInterval(Wa);Wa=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){return a=d.fx?d.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(c,e){var f=z.setTimeout(c,a);e.stop=function(){z.clearTimeout(f)}})};(function(){var a=N.createElement("input"),b=N.createElement("select").appendChild(N.createElement("option"));a.type="checkbox";V.checkOn=""!==a.value;V.optSelected=b.selected;a=N.createElement("input");a.value="t";a.type="radio";V.radioValue=
"t"===a.value})();var eb=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return Ga(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})}});d.extend({attr:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g)return"undefined"==typeof a.getAttribute?d.prop(a,b,c):(1===g&&d.isXMLDoc(a)||(f=d.attrHooks[b.toLowerCase()]||(d.expr.match.bool.test(b)?td:void 0)),void 0!==c?null===c?void d.removeAttr(a,b):f&&"set"in f&&void 0!==(e=f.set(a,
c,b))?e:(a.setAttribute(b,c+""),c):f&&"get"in f&&null!==(e=f.get(a,b))?e:(e=d.find.attr(a,b),null==e?void 0:e))},attrHooks:{type:{set:function(a,b){if(!V.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}}},removeAttr:function(a,b){var c=0,e=b&&b.match(sa);if(e&&1===a.nodeType)for(;b=e[c++];)a.removeAttribute(b)}});var td={set:function(a,b,c){return!1===b?d.removeAttr(a,c):a.setAttribute(c,c),c}};d.each(d.expr.match.bool.source.match(/\w+/g),
function(a,b){var c=eb[b]||d.find.attr;eb[b]=function(e,f,g){var k,m,q=f.toLowerCase();return g||(m=eb[q],eb[q]=k,k=null!=c(e,f,g)?q:null,eb[q]=m),k}});var ud=/^(?:input|select|textarea|button)$/i,vd=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return Ga(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})}});d.extend({prop:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g)return 1===g&&d.isXMLDoc(a)||(b=d.propFix[b]||
b,f=d.propHooks[b]),void 0!==c?f&&"set"in f&&void 0!==(e=f.set(a,c,b))?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");return b?parseInt(b,10):ud.test(a.nodeName)||vd.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});V.optSelected||(d.propHooks.selected={get:function(a){a=a.parentNode;return a&&a.parentNode&&a.parentNode.selectedIndex,null},set:function(a){a=a.parentNode;a&&(a.selectedIndex,a.parentNode&&
a.parentNode.selectedIndex)}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});d.fn.extend({addClass:function(a){var b,c,e,f,g,k,m=0;if(d.isFunction(a))return this.each(function(q){d(this).addClass(a.call(this,q,Ma(this)))});if("string"==typeof a&&a)for(b=a.match(sa)||[];c=this[m++];)if(f=Ma(c),e=1===c.nodeType&&" "+La(f)+" "){for(k=0;g=b[k++];)0>e.indexOf(" "+g+" ")&&(e+=g+" ");
e=La(e);f!==e&&c.setAttribute("class",e)}return this},removeClass:function(a){var b,c,e,f,g,k,m=0;if(d.isFunction(a))return this.each(function(q){d(this).removeClass(a.call(this,q,Ma(this)))});if(!arguments.length)return this.attr("class","");if("string"==typeof a&&a)for(b=a.match(sa)||[];c=this[m++];)if(f=Ma(c),e=1===c.nodeType&&" "+La(f)+" "){for(k=0;g=b[k++];)for(;-1<e.indexOf(" "+g+" ");)e=e.replace(" "+g+" "," ");e=La(e);f!==e&&c.setAttribute("class",e)}return this},toggleClass:function(a,b){var c=
typeof a;return"boolean"==typeof b&&"string"===c?b?this.addClass(a):this.removeClass(a):d.isFunction(a)?this.each(function(e){d(this).toggleClass(a.call(this,e,Ma(this),b),b)}):this.each(function(){var e,f;if("string"===c){var g=0;var k=d(this);for(f=a.match(sa)||[];e=f[g++];)k.hasClass(e)?k.removeClass(e):k.addClass(e)}else void 0!==a&&"boolean"!==c||(e=Ma(this),e&&G.set(this,"__className__",e),this.setAttribute&&this.setAttribute("class",e||!1===a?"":G.get(this,"__className__")||""))})},hasClass:function(a){var b,
c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+La(Ma(b))+" ").indexOf(a))return!0;return!1}});var wd=/\r/g;d.fn.extend({val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=d.isFunction(a),this.each(function(g){var k;1===this.nodeType&&(k=e?a.call(this,g,d(this).val()):a,null==k?k="":"number"==typeof k?k+="":d.isArray(k)&&(k=d.map(k,function(m){return null==m?"":m+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,k,"value")||
(this.value=k))});if(f)return b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()],b&&"get"in b&&void 0!==(c=b.get(f,"value"))?c:(c=f.value,"string"==typeof c?c.replace(wd,""):null==c?"":c)}});d.extend({valHooks:{option:{get:function(a){var b=d.find.attr(a,"value");return null!=b?b:La(d.text(a))}},select:{get:function(a){var b,c,e=a.options,f=a.selectedIndex,g="select-one"===a.type,k=g?null:[],m=g?f+1:e.length;for(c=0>f?m:g?f:0;c<m;c++)if(b=e[c],!(!b.selected&&c!==f||b.disabled||b.parentNode.disabled&&
d.nodeName(b.parentNode,"optgroup"))){if(a=d(b).val(),g)return a;k.push(a)}return k},set:function(a,b){for(var c,e=a.options,f=d.makeArray(b),g=e.length;g--;)b=e[g],(b.selected=-1<d.inArray(d.valHooks.option.get(b),f))&&(c=!0);return c||(a.selectedIndex=-1),f}}}});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){if(d.isArray(b))return a.checked=-1<d.inArray(d(a).val(),b)}};V.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});
var wc=/^(?:focusinfocus|focusoutblur)$/;d.extend(d.event,{trigger:function(a,b,c,e){var f,g,k,m,q,u=[c||N],p=ob.call(a,"type")?a.type:a;var x=ob.call(a,"namespace")?a.namespace.split("."):[];if(f=g=c=c||N,3!==c.nodeType&&8!==c.nodeType&&!wc.test(p+d.event.triggered)&&(-1<p.indexOf(".")&&(x=p.split("."),p=x.shift(),x.sort()),k=0>p.indexOf(":")&&"on"+p,a=a[d.expando]?a:new d.Event(p,"object"==typeof a&&a),a.isTrigger=e?2:3,a.namespace=x.join("."),a.rnamespace=a.namespace?new RegExp("(^|\\.)"+x.join("\\.(?:.*\\.|)")+
"(\\.|$)"):null,a.result=void 0,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),q=d.event.special[p]||{},e||!q.trigger||!1!==q.trigger.apply(c,b))){if(!e&&!q.noBubble&&!d.isWindow(c)){var C=q.delegateType||p;for(wc.test(C+p)||(f=f.parentNode);f;f=f.parentNode)u.push(f),g=f;g===(c.ownerDocument||N)&&u.push(g.defaultView||g.parentWindow||z)}for(x=0;(f=u[x++])&&!a.isPropagationStopped();)a.type=1<x?C:q.bindType||p,(m=(G.get(f,"events")||{})[a.type]&&G.get(f,"handle"))&&m.apply(f,b),(m=k&&f[k])&&
m.apply&&sb(f)&&(a.result=m.apply(f,b),!1===a.result&&a.preventDefault());return a.type=p,e||a.isDefaultPrevented()||q._default&&!1!==q._default.apply(u.pop(),b)||!sb(c)||k&&d.isFunction(c[p])&&!d.isWindow(c)&&(g=c[k],g&&(c[k]=null),d.event.triggered=p,c[p](),d.event.triggered=void 0,g&&(c[k]=g)),a.result}},simulate:function(a,b,c){a=d.extend(new d.Event,c,{type:a,isSimulated:!0});d.event.trigger(a,null,b)}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},
triggerHandler:function(a,b){var c=this[0];if(c)return d.event.trigger(a,b,c,!0)}});d.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),function(a,b){d.fn[b]=function(c,e){return 0<arguments.length?this.on(b,null,c,e):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});V.focusin="onfocusin"in z;V.focusin||
d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=function(e){d.event.simulate(b,e.target,d.event.fix(e))};d.event.special[b]={setup:function(){var e=this.ownerDocument||this,f=G.access(e,b);f||e.addEventListener(a,c,!0);G.access(e,b,(f||0)+1)},teardown:function(){var e=this.ownerDocument||this,f=G.access(e,b)-1;f?G.access(e,b,f):(e.removeEventListener(a,c,!0),G.remove(e,b))}}});var fb=z.location,xc=d.now(),Fb=/\?/;d.parseXML=function(a){if(!a||"string"!=typeof a)return null;try{var b=
(new z.DOMParser).parseFromString(a,"text/xml")}catch(c){b=void 0}return b&&!b.getElementsByTagName("parsererror").length||d.error("Invalid XML: "+a),b};var Nc=/\[\]$/,yc=/\r?\n/g,xd=/^(?:submit|button|image|reset|file)$/i,yd=/^(?:input|select|textarea|keygen)/i;d.param=function(a,b){var c,e=[],f=function(g,k){k=d.isFunction(k)?k():k;e[e.length]=encodeURIComponent(g)+"="+encodeURIComponent(null==k?"":k)};if(d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});
else for(c in a)xb(c,a[c],b,f);return e.join("&")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&yd.test(this.nodeName)&&!xd.test(a)&&(this.checked||!tc.test(a))}).map(function(a,b){a=d(this).val();return null==a?null:d.isArray(a)?d.map(a,function(c){return{name:b.name,value:c.replace(yc,
"\r\n")}}):{name:b.name,value:a.replace(yc,"\r\n")}}).get()}});var zd=/%20/g,Ad=/#.*$/,Bd=/([?&])_=[^&]*/,Cd=/^(.*?):[ \t]*([^\r\n]*)$/gm,Dd=/^(?:GET|HEAD)$/,Ed=/^\/\//,zc={},yb={},Ac="*/".concat("*"),Gb=N.createElement("a");Gb.href=fb.href;d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:fb.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(fb.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",
accepts:{"*":Ac,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":JSON.parse,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?zb(zb(a,d.ajaxSettings),b):zb(d.ajaxSettings,a)},ajaxPrefilter:fc(zc),ajaxTransport:fc(yb),
ajax:function(a,b){function c(K,ca,W,na){var L,ja,ea,R=ca;if(!ma){ma=!0;k&&z.clearTimeout(k);e=void 0;f=na||"";I.readyState=0<K?4:0;na=200<=K&&300>K||304===K;if(W){var U=p;for(var Ba=I,fa,M,Y,T,cb=U.contents,ua=U.dataTypes;"*"===ua[0];)ua.shift(),void 0===fa&&(fa=U.mimeType||Ba.getResponseHeader("Content-Type"));if(fa)for(M in cb)if(cb[M]&&cb[M].test(fa)){ua.unshift(M);break}if(ua[0]in W)Y=ua[0];else{for(M in W){if(!ua[0]||U.converters[M+" "+ua[0]]){Y=M;break}T||(T=M)}Y=Y||T}W=Y?(Y!==ua[0]&&ua.unshift(Y),
W[Y]):void 0;U=W}a:{W=p;fa=U;M=I;Y=na;var ka,ya,va;U={};Ba=W.dataTypes.slice();if(Ba[1])for(ka in W.converters)U[ka.toLowerCase()]=W.converters[ka];for(T=Ba.shift();T;)if(W.responseFields[T]&&(M[W.responseFields[T]]=fa),!va&&Y&&W.dataFilter&&(fa=W.dataFilter(fa,W.dataType)),va=T,T=Ba.shift())if("*"===T)T=va;else if("*"!==va&&va!==T){if(ka=U[va+" "+T]||U["* "+T],!ka)for(Ia in U)if(ya=Ia.split(" "),ya[1]===T&&(ka=U[va+" "+ya[0]]||U["* "+ya[0]])){!0===ka?ka=U[Ia]:!0!==U[Ia]&&(T=ya[0],Ba.unshift(ya[1]));
break}if(!0!==ka)if(ka&&W["throws"])fa=ka(fa);else try{fa=ka(fa)}catch(Da){var Ia={state:"parsererror",error:ka?Da:"No conversion from "+va+" to "+T};break a}}Ia={state:"success",data:fa}}U=Ia;na?(p.ifModified&&(ea=I.getResponseHeader("Last-Modified"),ea&&(d.lastModified[da]=ea),ea=I.getResponseHeader("etag"),ea&&(d.etag[da]=ea)),204===K||"HEAD"===p.type?R="nocontent":304===K?R="notmodified":(R=U.state,L=U.data,ja=U.error,na=!ja)):(ja=R,!K&&R||(R="error",0>K&&(K=0)));I.status=K;I.statusText=(ca||
R)+"";na?J.resolveWith(x,[L,R,I]):J.rejectWith(x,[I,R,ja]);I.statusCode(Q);Q=void 0;m&&C.trigger(na?"ajaxSuccess":"ajaxError",[I,p,na?L:ja]);A.fireWith(x,[I,R]);m&&(C.trigger("ajaxComplete",[I,p]),--d.active||d.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,k,m,q,u,p=d.ajaxSetup({},b),x=p.context||p,C=p.context&&(x.nodeType||x.jquery)?d(x):d.event,J=d.Deferred(),A=d.Callbacks("once memory"),Q=p.statusCode||{},P={},za={},ha="canceled",I={readyState:0,getResponseHeader:function(K){var ca;
if(ma){if(!g)for(g={};ca=Cd.exec(f);)g[ca[1].toLowerCase()]=ca[2];ca=g[K.toLowerCase()]}return null==ca?null:ca},getAllResponseHeaders:function(){return ma?f:null},setRequestHeader:function(K,ca){return null==ma&&(K=za[K.toLowerCase()]=za[K.toLowerCase()]||K,P[K]=ca),this},overrideMimeType:function(K){return null==ma&&(p.mimeType=K),this},statusCode:function(K){var ca;if(K)if(ma)I.always(K[I.status]);else for(ca in K)Q[ca]=[Q[ca],K[ca]];return this},abort:function(K){K=K||ha;return e&&e.abort(K),
c(0,K),this}};if(J.promise(I),p.url=((a||p.url||fb.href)+"").replace(Ed,fb.protocol+"//"),p.type=b.method||b.type||p.method||p.type,p.dataTypes=(p.dataType||"*").toLowerCase().match(sa)||[""],null==p.crossDomain){a=N.createElement("a");try{a.href=p.url,a.href=a.href,p.crossDomain=Gb.protocol+"//"+Gb.host!=a.protocol+"//"+a.host}catch(K){p.crossDomain=!0}}if(p.data&&p.processData&&"string"!=typeof p.data&&(p.data=d.param(p.data,p.traditional)),gc(zc,p,b,I),ma)return I;(m=d.event&&p.global)&&0===d.active++&&
d.event.trigger("ajaxStart");p.type=p.type.toUpperCase();p.hasContent=!Dd.test(p.type);var da=p.url.replace(Ad,"");p.hasContent?p.data&&p.processData&&0===(p.contentType||"").indexOf("application/x-www-form-urlencoded")&&(p.data=p.data.replace(zd,"+")):(u=p.url.slice(da.length),p.data&&(da+=(Fb.test(da)?"&":"?")+p.data,delete p.data),!1===p.cache&&(da=da.replace(Bd,"$1"),u=(Fb.test(da)?"&":"?")+"_="+xc++ +u),p.url=da+u);p.ifModified&&(d.lastModified[da]&&I.setRequestHeader("If-Modified-Since",d.lastModified[da]),
d.etag[da]&&I.setRequestHeader("If-None-Match",d.etag[da]));(p.data&&p.hasContent&&!1!==p.contentType||b.contentType)&&I.setRequestHeader("Content-Type",p.contentType);I.setRequestHeader("Accept",p.dataTypes[0]&&p.accepts[p.dataTypes[0]]?p.accepts[p.dataTypes[0]]+("*"!==p.dataTypes[0]?", "+Ac+"; q=0.01":""):p.accepts["*"]);for(q in p.headers)I.setRequestHeader(q,p.headers[q]);if(p.beforeSend&&(!1===p.beforeSend.call(x,I,p)||ma))return I.abort();if(ha="abort",A.add(p.complete),I.done(p.success),I.fail(p.error),
e=gc(yb,p,b,I)){if(I.readyState=1,m&&C.trigger("ajaxSend",[I,p]),ma)return I;p.async&&0<p.timeout&&(k=z.setTimeout(function(){I.abort("timeout")},p.timeout));try{var ma=!1;e.send(P,c)}catch(K){if(ma)throw K;c(-1,K)}}else c(-1,"No Transport");return I},getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(c,e,f,g){return d.isFunction(e)&&(g=g||f,f=e,e=void 0),d.ajax(d.extend({url:c,type:b,dataType:g,
data:e,success:f},d.isPlainObject(c)&&c))}});d._evalUrl=function(a){return d.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,"throws":!0})};d.fn.extend({wrapAll:function(a){var b;return this[0]&&(d.isFunction(a)&&(a=a.call(this[0])),b=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var c=this;c.firstElementChild;)c=c.firstElementChild;return c}).append(this)),this},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,
b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(a){return this.parent(a).not("body").each(function(){d(this).replaceWith(this.childNodes)}),this}});d.expr.pseudos.hidden=function(a){return!d.expr.pseudos.visible(a)};d.expr.pseudos.visible=function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};d.ajaxSettings.xhr=
function(){try{return new z.XMLHttpRequest}catch(a){}};var Fd={0:200,1223:204},gb=d.ajaxSettings.xhr();V.cors=!!gb&&"withCredentials"in gb;V.ajax=gb=!!gb;d.ajaxTransport(function(a){var b,c;if(V.cors||gb&&!a.crossDomain)return{send:function(e,f){var g,k=a.xhr();if(k.open(a.type,a.url,a.async,a.username,a.password),a.xhrFields)for(g in a.xhrFields)k[g]=a.xhrFields[g];a.mimeType&&k.overrideMimeType&&k.overrideMimeType(a.mimeType);a.crossDomain||e["X-Requested-With"]||(e["X-Requested-With"]="XMLHttpRequest");
for(g in e)k.setRequestHeader(g,e[g]);b=function(m){return function(){b&&(b=c=k.onload=k.onerror=k.onabort=k.onreadystatechange=null,"abort"===m?k.abort():"error"===m?"number"!=typeof k.status?f(0,"error"):f(k.status,k.statusText):f(Fd[k.status]||k.status,k.statusText,"text"!==(k.responseType||"text")||"string"!=typeof k.responseText?{binary:k.response}:{text:k.responseText},k.getAllResponseHeaders()))}};k.onload=b();c=k.onerror=b("error");void 0!==k.onabort?k.onabort=c:k.onreadystatechange=function(){4===
k.readyState&&z.setTimeout(function(){b&&c()})};b=b("abort");try{k.send(a.hasContent&&a.data||null)}catch(m){if(b)throw m;}},abort:function(){b&&b()}}});d.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},converters:{"text script":function(a){return d.globalEval(a),a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&
(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(g){b.remove();c=null;g&&f("error"===g.type?404:200,g.type)});N.head.appendChild(b[0])},abort:function(){c&&c()}}}});var Bc=[],Hb=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Bc.pop()||d.expando+"_"+xc++;return this[a]=!0,a}});d.ajaxPrefilter("json jsonp",
function(a,b,c){var e,f,g,k=!1!==a.jsonp&&(Hb.test(a.url)?"url":"string"==typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Hb.test(a.data)&&"data");if(k||"jsonp"===a.dataTypes[0])return e=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,k?a[k]=a[k].replace(Hb,"$1"+e):!1!==a.jsonp&&(a.url+=(Fb.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){return g||d.error(e+" was not called"),g[0]},a.dataTypes[0]="json",
f=z[e],z[e]=function(){g=arguments},c.always(function(){void 0===f?d(z).removeProp(e):z[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,Bc.push(e));g&&d.isFunction(f)&&f(g[0]);g=f=void 0}),"script"});V.createHTMLDocument=function(){var a=N.implementation.createHTMLDocument("").body;return a.innerHTML="<form></form><form></form>",2===a.childNodes.length}();d.parseHTML=function(a,b,c){if("string"!=typeof a)return[];"boolean"==typeof b&&(c=b,b=!1);var e,f,g;return b||(V.createHTMLDocument?(b=N.implementation.createHTMLDocument(""),
e=b.createElement("base"),e.href=N.location.href,b.head.appendChild(e)):b=N),f=qc.exec(a),g=!c&&[],f?[b.createElement(f[1])]:(f=Nb([a],b,g),g&&g.length&&d(g).remove(),d.merge([],f.childNodes))};d.fn.load=function(a,b,c){var e,f,g,k=this,m=a.indexOf(" ");return-1<m&&(e=La(a.slice(m)),a=a.slice(0,m)),d.isFunction(b)?(c=b,b=void 0):b&&"object"==typeof b&&(f="POST"),0<k.length&&d.ajax({url:a,type:f||"GET",dataType:"html",data:b}).done(function(q){g=arguments;k.html(e?d("<div>").append(d.parseHTML(q)).find(e):
q)}).always(c&&function(q,u){k.each(function(){c.apply(this,g||[q.responseText,u,q])})}),this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(c){return this.on(b,c)}});d.expr.pseudos.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length};d.offset={setOffset:function(a,b,c){var e,f,g,k=d.css(a,"position"),m=d(a),q={};"static"===k&&(a.style.position="relative");var u=m.offset();var p=d.css(a,"top");var x=
d.css(a,"left");("absolute"===k||"fixed"===k)&&-1<(p+x).indexOf("auto")?(e=m.position(),g=e.top,f=e.left):(g=parseFloat(p)||0,f=parseFloat(x)||0);d.isFunction(b)&&(b=b.call(a,c,d.extend({},u)));null!=b.top&&(q.top=b.top-u.top+g);null!=b.left&&(q.left=b.left-u.left+f);"using"in b?b.using.call(a,q):m.css(q)}};d.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(k){d.offset.setOffset(this,a,k)});var b,c,e,f,g=this[0];if(g)return g.getClientRects().length?(e=g.getBoundingClientRect(),
e.width||e.height?(f=g.ownerDocument,c=hc(f),b=f.documentElement,{top:e.top+c.pageYOffset-b.clientTop,left:e.left+c.pageXOffset-b.clientLeft}):e):{top:0,left:0}},position:function(){if(this[0]){var a,b,c=this[0],e={top:0,left:0};return"fixed"===d.css(c,"position")?b=c.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),d.nodeName(a[0],"html")||(e=a.offset()),e={top:e.top+d.css(a[0],"borderTopWidth",!0),left:e.left+d.css(a[0],"borderLeftWidth",!0)}),{top:b.top-e.top-d.css(c,"marginTop",
!0),left:b.left-e.left-d.css(c,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;return a||tb})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(e){return Ga(this,function(f,g,k){var m=hc(f);return void 0===k?m?m[b]:f[g]:void(m?m.scrollTo(c?m.pageXOffset:k,c?k:m.pageYOffset):f[g]=k)},a,e,arguments.length)}});d.each(["top","left"],function(a,
b){d.cssHooks[b]=Wb(V.pixelPosition,function(c,e){if(e)return e=bb(c,b),wb.test(e)?d(c).position()[b]+"px":e})});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(f,g){var k=arguments.length&&(c||"boolean"!=typeof f),m=c||(!0===f||!0===g?"margin":"border");return Ga(this,function(q,u,p){var x;return d.isWindow(q)?0===e.indexOf("outer")?q["inner"+a]:q.document.documentElement["client"+a]:9===q.nodeType?(x=q.documentElement,
Math.max(q.body["scroll"+a],x["scroll"+a],q.body["offset"+a],x["offset"+a],x["client"+a])):void 0===p?d.css(q,u,m):d.style(q,u,p,m)},b,k?f:void 0,k)}})});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});d.parseJSON=JSON.parse;"function"==typeof define&&define.amd&&define("jquery",[],function(){return d});
var Gd=z.jQuery,Hd=z.$;return d.noConflict=function(a){return z.$===d&&(z.$=Hd),a&&z.jQuery===d&&(z.jQuery=Gd),d},X||(z.jQuery=z.$=d),d});process=process||{env:{NODE_ENV:"development"}};
function getPipPlace_jq(z){var X=$.ajax({url:"/webservice/getPipPlace?pipId="+z,type:"GET",dataType:"jsonp",crossDomain:!0,contentType:"application/json",jsonp:jsonpKey,cache:!1});X.done(function(oa,wa,Ja){oa=JSON.parse(JSON.stringify(oa));oa.pip&&($("#pip-place-"+z).html(oa.pip),replaceSeoHtmlLink("#pip-place-"+z))});X.fail(function(oa,wa,Ja){});X.always(function(){})}
function getPipPlace(z){var X=new XMLHttpRequest;X.onload=function(){X.readyState==XMLHttpRequest.DONE&&200==X.status&&(document.getElementById("pip-place-"+z).innerHTML=X.responseText,replaceSeoHtmlLink("#pip-place-"+z))};X.open("GET","/webservice/getPipPlace?pipId="+z,!0);X.send()}process=process||{env:{NODE_ENV:"development"}};
var siteLang="ru_RU",jsonpKey="ovJsonP",errorMessageTtl="Error",successMessageTtl="Success",errorEmptyData="Response is empty",errorCheckData="Check input data",errorCheckDate="Format date is incorrect",errorSelectedEmpty="You have not selected any options",notEnoughRights="You are not authorized for this operation";
if("ru"==siteLang||"ru_RU"==siteLang)errorMessageTtl="\u041e\u0448\u0438\u0431\u043a\u0430",successMessageTtl="\u0423\u0441\u043f\u0435\u0448\u043d\u043e",errorEmptyData="\u041e\u0442\u0432\u0435\u0442 \u0441\u0435\u0440\u0432\u0435\u0440\u0430 \u043d\u0435 \u0432\u0435\u0440\u043d\u0443\u043b \u0434\u0430\u043d\u043d\u044b\u0445",errorCheckData="\u041f\u0440\u043e\u0432\u0435\u0440\u044c\u0442\u0435 \u0432\u0432\u0435\u0434\u0435\u043d\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435",errorCheckDate=
"\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u0434\u0430\u0442\u044b",errorSelectedEmpty="\u0412\u044b \u043d\u0435 \u0432\u044b\u0431\u0440\u0430\u043b\u0438 \u043d\u0438 \u043e\u0434\u043d\u043e\u0433\u043e \u0432\u0430\u0440\u0438\u0430\u043d\u0442\u0430",notEnoughRights="\u0412\u044b \u043d\u0435 \u0438\u043c\u0435\u0435\u0442\u0435 \u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043f\u0440\u0430\u0432 \u0434\u043b\u044f \u0434\u0430\u043d\u043d\u043e\u0439 \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438";
process=process||{env:{NODE_ENV:"development"}};