var process=process||{env:{NODE_ENV:"development"}};
(function(m,r,e,k){function q(a){var b=a.currentTarget,c=a.data?a.data.options:{},g=a.data?a.data.items:[],f="",l=0;a.preventDefault();a.stopPropagation();e(b).attr("data-fancybox")&&(f=e(b).data("fancybox"));f?(g=g.length?g.filter('[data-fancybox="'+f+'"]'):e("[data-fancybox="+f+"]"),l=g.index(b)):g=[b];e.fancybox.open(g,c,l)}if(!e)return k;var u={speed:330,loop:!0,opacity:"auto",margin:[44,0],gutter:30,infobar:!0,buttons:!0,slideShow:!0,fullScreen:!0,thumbs:!0,closeBtn:!0,smallBtn:"auto",image:{preload:"auto",
protect:!1},ajax:{settings:{data:{fancybox:!0}}},iframe:{tpl:'<iframe id="fancybox-frame{rnd}" name="fancybox-frame{rnd}" class="fancybox-iframe" frameborder="0" vspace="0" hspace="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen allowtransparency="true" src=""></iframe>',preload:!0,scrolling:"no",css:{}},baseClass:"",slideClass:"",baseTpl:'<div class="fancybox-container" role="dialog" tabindex="-1"><div class="fancybox-bg"></div><div class="fancybox-controls"><div class="fancybox-infobar"><button data-fancybox-previous class="fancybox-button fancybox-button--left" title="Previous"></button><div class="fancybox-infobar__body"><span class="js-fancybox-index"></span>&nbsp;/&nbsp;<span class="js-fancybox-count"></span></div><button data-fancybox-next class="fancybox-button fancybox-button--right" title="Next"></button></div><div class="fancybox-buttons"><button data-fancybox-close class="fancybox-button fancybox-button--close" title="Close (Esc)"></button></div></div><div class="fancybox-slider-wrap"><div class="fancybox-slider"></div></div><div class="fancybox-caption-wrap"><div class="fancybox-caption"></div></div></div>',
spinnerTpl:'<div class="fancybox-loading"></div>',errorTpl:'<div class="fancybox-error"><p>The requested content cannot be loaded. <br /> Please try again later.<p></div>',closeTpl:'<button data-fancybox-close class="fancybox-close-small"></button>',parentEl:"body",touch:!0,keyboard:!0,focus:!0,closeClickOutside:!0,beforeLoad:e.noop,afterLoad:e.noop,beforeMove:e.noop,afterMove:e.noop,onComplete:e.noop,onInit:e.noop,beforeClose:e.noop,afterClose:e.noop,onActivate:e.noop,onDeactivate:e.noop},w=e(m),
n=e(r),d=0,h=function(){return m.requestAnimationFrame||m.webkitRequestAnimationFrame||m.mozRequestAnimationFrame||function(a){m.setTimeout(a,1E3/60)}}(),p=function(a){"function"===typeof e&&a instanceof e&&(a=a[0]);a=a.getBoundingClientRect();return 0<a.bottom&&0<a.right&&a.left<(m.innerWidth||r.documentElement.clientWidth)&&a.top<(m.innerHeight||r.documentElement.clientHeight)},x=function(a,b,c){this.opts=e.extend(!0,{index:c},u,b||{});this.id=this.opts.id||++d;this.group=[];this.currIndex=parseInt(this.opts.index,
10)||0;this.prevPos=this.prevIndex=null;this.currPos=0;this.firstRun=null;this.createGroup(a);this.group.length&&(this.$lastFocus=e(r.activeElement).blur(),this.slides={},this.init(a))};e.extend(x.prototype,{init:function(){var a=!1;this.scrollTop=n.scrollTop();this.scrollLeft=n.scrollLeft();if(!e.fancybox.getInstance()){var b=e("body").width();e("html").addClass("fancybox-enabled");e.fancybox.isTouch?(e.each(this.group,function(c,g){if("image"!==g.type&&"iframe"!==g.type)return a=!0,!1}),a&&e("body").css({position:"fixed",
width:b,top:-1*this.scrollTop})):(b=e("body").width()-b,1<b&&e('<style id="fancybox-noscroll" type="text/css">').html(".compensate-for-scrollbar, .fancybox-enabled body { margin-right: "+b+"px; }").appendTo("head"))}b=e(this.opts.baseTpl).attr("id","fancybox-container-"+this.id).data("FancyBox",this).addClass(this.opts.baseClass).hide().prependTo(this.opts.parentEl);this.$refs={container:b,bg:b.find(".fancybox-bg"),controls:b.find(".fancybox-controls"),buttons:b.find(".fancybox-buttons"),slider_wrap:b.find(".fancybox-slider-wrap"),
slider:b.find(".fancybox-slider"),caption:b.find(".fancybox-caption")};this.trigger("onInit");this.activate();this.current||this.jumpTo(this.currIndex)},createGroup:function(a){var b=this;a=e.makeArray(a);e.each(a,function(c,g){c={};var f={},l=[];if(e.isPlainObject(g))c=g,f=g.opts||{};else if("object"===e.type(g)&&e(g).length){var v=e(g);l=v.data();f="options"in l?l.options:{};f="object"===e.type(f)?f:{};c.type="type"in l?l.type:f.type;c.src="src"in l?l.src:f.src||v.attr("href");f.width="width"in
l?l.width:f.width;f.height="height"in l?l.height:f.height;f.thumb="thumb"in l?l.thumb:f.thumb;f.selector="selector"in l?l.selector:f.selector;"srcset"in l&&(f.image={srcset:l.srcset});f.$orig=v}else c={type:"html",content:g+""};c.opts=e.extend(!0,{},b.opts,f);var t=c.type;var y=c.src||"";t||(c.content?t="html":y.match(/(^data:image\/[a-z0-9+\/=]*,)|(\.(jp(e|g|eg)|gif|png|bmp|webp|svg|ico)((\?|#).*)?$)/i)?t="image":y.match(/\.(pdf)((\?|#).*)?$/i)?t="pdf":"#"===y.charAt(0)&&(t="inline"),c.type=t);c.index=
b.group.length;c.opts.$orig&&!c.opts.$orig.length&&delete c.opts.$orig;!c.opts.$thumb&&c.opts.$orig&&(c.opts.$thumb=c.opts.$orig.find("img:first"));c.opts.$thumb&&!c.opts.$thumb.length&&delete c.opts.$thumb;"function"===e.type(c.opts.caption)?c.opts.caption=c.opts.caption.apply(g,[b,c]):"caption"in l?c.opts.caption=l.caption:f.$orig&&(c.opts.caption=v.attr("title"));c.opts.caption=c.opts.caption===k?"":c.opts.caption+"";"ajax"===t&&(g=y.split(/\s+/,2),1<g.length&&(c.src=g.shift(),c.opts.selector=
g.shift()));"auto"==c.opts.smallBtn&&(-1<e.inArray(t,["html","inline","ajax"])?(c.opts.buttons=!1,c.opts.smallBtn=!0):c.opts.smallBtn=!1);"pdf"===t&&(c.type="iframe",c.opts.closeBtn=!0,c.opts.smallBtn=!1,c.opts.iframe.preload=!1);c.opts.modal&&e.extend(!0,c.opts,{infobar:0,buttons:0,keyboard:0,slideShow:0,fullScreen:0,closeClickOutside:0});b.group.push(c)})},addEvents:function(){var a=this;a.removeEvents();a.$refs.container.on("click.fb-close","[data-fancybox-close]",function(b){b.stopPropagation();
b.preventDefault();a.close(b)}).on("click.fb-previous","[data-fancybox-previous]",function(b){b.stopPropagation();b.preventDefault();a.previous()}).on("click.fb-next","[data-fancybox-next]",function(b){b.stopPropagation();b.preventDefault();a.next()});e(m).on("orientationchange.fb resize.fb",function(b){h(function(){b&&b.originalEvent&&"resize"===b.originalEvent.type?a.update():(a.$refs.slider_wrap.hide(),h(function(){a.$refs.slider_wrap.show();a.update()}))})});n.on("focusin.fb",function(b){var c=
e.fancybox?e.fancybox.getInstance():null;!c||e(b.target).hasClass("fancybox-container")||e.contains(c.$refs.container[0],b.target)||(b.stopPropagation(),c.focus(),w.scrollTop(a.scrollTop).scrollLeft(a.scrollLeft))});n.on("keydown.fb",function(b){var c=a.current,g=b.keyCode||b.which;if(c&&c.opts.keyboard&&!e(b.target).is("input")&&!e(b.target).is("textarea"))if(8===g||27===g)b.preventDefault(),a.close(b);else switch(g){case 37:case 38:b.preventDefault();a.previous();break;case 39:case 40:b.preventDefault();
a.next();break;case 80:case 32:b.preventDefault();a.SlideShow&&(b.preventDefault(),a.SlideShow.toggle());break;case 70:a.FullScreen&&(b.preventDefault(),a.FullScreen.toggle());break;case 71:a.Thumbs&&(b.preventDefault(),a.Thumbs.toggle())}})},removeEvents:function(){w.off("scroll.fb resize.fb orientationchange.fb");n.off("keydown.fb focusin.fb click.fb-close");this.$refs.container.off("click.fb-close click.fb-previous click.fb-next")},previous:function(a){this.jumpTo(this.currIndex-1,a)},next:function(a){this.jumpTo(this.currIndex+
1,a)},jumpTo:function(a,b){var c=this,g;var f=c.firstRun=null===c.firstRun;var l=g=a=parseInt(a,10);var v=c.current?c.current.opts.loop:!1;if(!c.isAnimating&&(l!=c.currIndex||f)){if(1<c.group.length&&v)l%=c.group.length,l=0>l?c.group.length+l:l,2==c.group.length?g=a-c.currIndex+c.currPos:(g=l-c.currIndex+c.currPos,Math.abs(c.currPos-(g+c.group.length))<Math.abs(c.currPos-g)?g+=c.group.length:Math.abs(c.currPos-(g-c.group.length))<Math.abs(c.currPos-g)&&(g-=c.group.length));else if(!c.group[l]){c.update(!1,
!1,b);return}c.current&&(c.current.$slide.removeClass("fancybox-slide--current fancybox-slide--complete"),c.updateSlide(c.current,!0));c.prevIndex=c.currIndex;c.prevPos=c.currPos;c.currIndex=l;c.currPos=g;c.current=c.createSlide(g);1<c.group.length&&((c.opts.loop||0<=g-1)&&c.createSlide(g-1),(c.opts.loop||g+1<c.group.length)&&c.createSlide(g+1));c.current.isMoved=!1;c.current.isComplete=!1;b=parseInt(b===k?1.5*c.current.opts.speed:b,10);c.trigger("beforeMove");c.updateControls();f&&(c.current.$slide.addClass("fancybox-slide--current"),
c.$refs.container.show(),h(function(){c.$refs.bg.css("transition-duration",c.current.opts.speed+"ms");c.$refs.container.addClass("fancybox-container--ready")}));c.update(!0,!1,f?0:b,function(){c.afterMove()});c.loadSlide(c.current);f&&c.current.$ghost||c.preload()}},createSlide:function(a){var b=a%this.group.length;b=0>b?this.group.length+b:b;if(!this.slides[a]&&this.group[b]){if(this.opts.loop&&2<this.group.length)for(c in this.slides)if(this.slides[c].index===b)return b=this.slides[c],b.pos=a,this.slides[a]=
b,delete this.slides[c],this.updateSlide(b),b;var c=e('<div class="fancybox-slide"></div>').appendTo(this.$refs.slider);this.slides[a]=e.extend(!0,{},this.group[b],{pos:a,$slide:c,isMoved:!1,isLoaded:!1})}return this.slides[a]},zoomInOut:function(a,b,c){var g=this,f=g.current,l=f.$placeholder,v=f.opts.opacity,t=f.opts.$thumb,y=t?t.offset():0,z=f.$slide.offset();if(!(l&&f.isMoved&&y&&p(t))||"In"===a&&!g.firstRun)return!1;e.fancybox.stop(l);g.isAnimating=!0;y={top:y.top-z.top+parseFloat(t.css("border-top-width")||
0),left:y.left-z.left+parseFloat(t.css("border-left-width")||0),width:t.width(),height:t.height(),scaleX:1,scaleY:1};"auto"==v&&(v=.1<Math.abs(f.width/f.height-y.width/y.height));"In"===a?(t=y,y=g.getFitPos(f),y.scaleX=y.width/t.width,y.scaleY=y.height/t.height,v&&(t.opacity=.1,y.opacity=1)):(t=e.fancybox.getTranslate(l),f.$ghost&&(f.$ghost.show(),f.$image&&f.$image.remove()),t.scaleX=t.width/y.width,t.scaleY=t.height/y.height,t.width=y.width,t.height=y.height,v&&(y.opacity=0));g.updateCursor(y.width,
y.height);delete y.width;delete y.height;e.fancybox.setTranslate(l,t);l.show();g.trigger("beforeZoom"+a);l.css("transition","all "+b+"ms");e.fancybox.setTranslate(l,y);setTimeout(function(){l.css("transition","none");var A=e.fancybox.getTranslate(l);A.scaleX=1;A.scaleY=1;e.fancybox.setTranslate(l,A);g.trigger("afterZoom"+a);c.apply(g);g.isAnimating=!1},b);return!0},canPan:function(){var a=this.current,b=a.$placeholder,c=!1;b&&(c=this.getFitPos(a),c=1<Math.abs(b.width()-c.width)||1<Math.abs(b.height()-
c.height));return c},isScaledDown:function(){var a=this.current,b=a.$placeholder,c=!1;b&&(c=e.fancybox.getTranslate(b),c=c.width<a.width||c.height<a.height);return c},scaleToActual:function(a,b,c){var g=this,f=g.current,l=f.$placeholder,v=parseInt(f.$slide.width(),10),t=parseInt(f.$slide.height(),10),y=f.width,z=f.height;if(l){g.isAnimating=!0;a=a===k?.5*v:a;b=b===k?.5*t:b;var A=e.fancybox.getTranslate(l);var C=y/A.width;var D=z/A.height;var E=.5*v-.5*y;var B=.5*t-.5*z;y>v&&(E=A.left*C-(a*C-a),0<
E&&(E=0),E<v-y&&(E=v-y));z>t&&(B=A.top*D-(b*D-b),0<B&&(B=0),B<t-z&&(B=t-z));g.updateCursor(y,z);e.fancybox.animate(l,null,{top:B,left:E,scaleX:C,scaleY:D},c||f.opts.speed,function(){g.isAnimating=!1})}},scaleToFit:function(a){var b=this,c=b.current,g=c.$placeholder;if(g){b.isAnimating=!0;var f=b.getFitPos(c);b.updateCursor(f.width,f.height);e.fancybox.animate(g,null,{top:f.top,left:f.left,scaleX:f.width/g.width(),scaleY:f.height/g.height()},a||c.opts.speed,function(){b.isAnimating=!1})}},getFitPos:function(a){var b=
a.$placeholder||a.$content,c=a.width,g=a.height,f=a.opts.margin;if(!b||!b.length||!c&&!g)return!1;"number"===e.type(f)&&(f=[f,f]);2==f.length&&(f=[f[0],f[1],f[0],f[1]]);800>w.width()&&(f=[0,0,0,0]);b=parseInt(a.$slide.width(),10)-(f[1]+f[3]);a=parseInt(a.$slide.height(),10)-(f[0]+f[2]);var l=Math.min(1,b/c,a/g);c=Math.floor(l*c);g=Math.floor(l*g);return{top:Math.floor(.5*(a-g))+f[0],left:Math.floor(.5*(b-c))+f[3],width:c,height:g}},update:function(a,b,c,g){var f=this;if(!0!==f.isAnimating&&f.current){var l=
f.current.pos*Math.floor(f.current.$slide.width())*-1-f.current.pos*f.current.opts.gutter;c=parseInt(c,10)||0;e.fancybox.stop(f.$refs.slider);!1===a?f.updateSlide(f.current,b):e.each(f.slides,function(v,t){f.updateSlide(t,b)});c?e.fancybox.animate(f.$refs.slider,null,{top:0,left:l},c,function(){f.current.isMoved=!0;"function"===e.type(g)&&g.apply(f)}):(e.fancybox.setTranslate(f.$refs.slider,{top:0,left:l}),f.current.isMoved=!0,"function"===e.type(g)&&g.apply(f))}},updateSlide:function(a,b){var c=
a.$placeholder;if((a=a||this.current)&&!this.isClosing){var g=a.pos*Math.floor(a.$slide.width())+a.pos*a.opts.gutter;g!==a.leftPos&&(e.fancybox.setTranslate(a.$slide,{top:0,left:g}),a.leftPos=g);!1!==b&&c&&(e.fancybox.setTranslate(c,this.getFitPos(a)),a.pos===this.currPos&&this.updateCursor());a.$slide.trigger("refresh");this.trigger("onUpdate",a)}},updateCursor:function(a,b){var c=this.$refs.container.removeClass("fancybox-controls--canzoomIn fancybox-controls--canzoomOut fancybox-controls--canGrab");
!this.isClosing&&this.opts.touch&&((a=a!==k&&b!==k?a<this.current.width&&b<this.current.height:this.isScaledDown())?c.addClass("fancybox-controls--canzoomIn"):2>this.group.length?c.addClass("fancybox-controls--canzoomOut"):c.addClass("fancybox-controls--canGrab"))},loadSlide:function(a){var b=this;if(a&&!a.isLoaded&&!a.isLoading){a.isLoading=!0;b.trigger("beforeLoad",a);var c=a.type;var g=a.$slide;g.off("refresh").trigger("onReset").addClass("fancybox-slide--"+(c||"unknown")).addClass(a.opts.slideClass);
switch(c){case "image":b.setImage(a);break;case "iframe":b.setIframe(a);break;case "html":b.setContent(a,a.content);break;case "inline":e(a.src).length?b.setContent(a,e(a.src)):b.setError(a);break;case "ajax":b.showLoading(a);var f=e.ajax(e.extend({},a.opts.ajax.settings,{url:a.src,success:function(l,v){"success"===v&&b.setContent(a,l)},error:function(l,v){l&&"abort"!==v&&b.setError(a)}}));g.one("onReset",function(){f.abort()});break;default:b.setError(a)}return!0}},setImage:function(a){var b=this,
c=a.opts.image.srcset;if(a.isLoaded&&!a.hasError)b.afterLoad(a);else{if(c){var g=m.devicePixelRatio||1;var f=m.innerWidth*g;c=c.split(",").map(function(y){var z={};y.trim().split(/\s+/).forEach(function(A,C){var D=parseInt(A.substring(0,A.length-1),10);if(0===C)return z.url=A;D&&(z.value=D,z.postfix=A[A.length-1])});return z});c.sort(function(y,z){return y.value-z.value});for(var l=0;l<c.length;l++){var v=c[l];if("w"===v.postfix&&v.value>=f||"x"===v.postfix&&v.value>=g){var t=v;break}}!t&&c.length&&
(t=c[c.length-1]);t&&(a.src=t.url,a.width&&a.height&&"w"==t.postfix&&(a.height=a.width/a.height*t.value,a.width=t.value))}a.$placeholder=e('<div class="fancybox-placeholder"></div>').hide().appendTo(a.$slide);!1!==a.opts.preload&&a.opts.width&&a.opts.height&&(a.opts.thumb||a.opts.$thumb)?(a.width=a.opts.width,a.height=a.opts.height,a.$ghost=e("<img />").one("load error",function(){b.isClosing||(e("<img/>")[0].src=a.src,b.revealImage(a,function(){b.setBigImage(a);b.firstRun&&a.index===b.currIndex&&
b.preload()}))}).addClass("fancybox-image").appendTo(a.$placeholder).attr("src",a.opts.thumb||a.opts.$thumb.attr("src"))):b.setBigImage(a)}},setBigImage:function(a){var b=this,c=e("<img />");a.$image=c.one("error",function(){b.setError(a)}).one("load",function(){clearTimeout(a.timouts);a.timouts=null;b.isClosing||(a.width=this.naturalWidth,a.height=this.naturalHeight,a.opts.image.srcset&&c.attr("sizes","100vw").attr("srcset",a.opts.image.srcset),b.afterLoad(a),a.$ghost&&(a.timouts=setTimeout(function(){a.$ghost.hide()},
350)))}).addClass("fancybox-image").attr("src",a.src).appendTo(a.$placeholder);c[0].complete?c.trigger("load"):c[0].error?c.trigger("error"):a.timouts=setTimeout(function(){c[0].complete||a.hasError||b.showLoading(a)},150);if(a.opts.image.protect)e('<div class="fancybox-spaceball"></div>').appendTo(a.$placeholder).on("contextmenu.fb",function(g){2==g.button&&g.preventDefault();return!0})},revealImage:function(a,b){b=b||e.noop;"image"!==a.type||a.hasError||!0===a.isRevealed?b.apply(this):(a.isRevealed=
!0,a.pos===this.currPos&&this.zoomInOut("In",a.opts.speed,b)||(a.$ghost&&!a.isLoaded&&this.updateSlide(a,!0),a.pos===this.currPos?e.fancybox.animate(a.$placeholder,{opacity:0},{opacity:1},300,b):a.$placeholder.show(),b.apply(this)))},setIframe:function(a){var b=this,c=a.opts.iframe,g=a.$slide;a.$content=e('<div class="fancybox-content"></div>').css(c.css).appendTo(g);var f=e(c.tpl.replace(/\{rnd\}/g,(new Date).getTime())).attr("scrolling",e.fancybox.isTouch?"auto":c.scrolling).appendTo(a.$content);
c.preload?(a.$content.addClass("fancybox-tmp"),b.showLoading(a),f.on("load.fb error.fb",function(l){this.isReady=1;a.$slide.trigger("refresh");b.afterLoad(a)}),g.on("refresh.fb",function(){var l=a.$content;if(1===f[0].isReady){try{var v=f.contents();var t=v.find("body")}catch(y){}t&&t.length&&(c.css.width===k||c.css.height===k)&&(v=f[0].contentWindow.document.documentElement.scrollWidth,v=Math.ceil(t.outerWidth(!0)+(l.width()-v)),t=Math.ceil(t.outerHeight(!0)),l.css({width:c.css.width===k?v+(l.outerWidth()-
l.innerWidth()):c.css.width,height:c.css.height===k?t+(l.outerHeight()-l.innerHeight()):c.css.height}));l.removeClass("fancybox-tmp")}})):this.afterLoad(a);f.attr("src",a.src);a.opts.smallBtn&&a.$content.prepend(a.opts.closeTpl);g.one("onReset",function(){try{e(this).find("iframe").hide().attr("src","//about:blank")}catch(l){}e(this).empty();a.isLoaded=!1})},setContent:function(a,b){this.isClosing||(this.hideLoading(a),a.$slide.empty(),b&&b.hasOwnProperty&&b instanceof e&&b.parent().length?(b.data("placeholder")&&
b.parents(".fancybox-slide").trigger("onReset"),b.data({placeholder:e("<div></div>").hide().insertAfter(b)}).css("display","inline-block")):("string"===e.type(b)&&(b=e("<div>").append(b).contents(),3===b[0].nodeType&&(b=e("<div>").html(b))),a.opts.selector&&(b=e("<div>").html(b).find(a.opts.selector))),a.$slide.one("onReset",function(){var c=b&&b.hasOwnProperty&&b instanceof e?b.data("placeholder"):0;c&&(b.hide().replaceAll(c),b.data("placeholder",null));a.hasError||(e(this).empty(),a.isLoaded=!1)}),
a.$content=e(b).appendTo(a.$slide),!0===a.opts.smallBtn&&a.$content.find(".fancybox-close-small").remove().end().eq(0).append(a.opts.closeTpl),this.afterLoad(a))},setError:function(a){a.hasError=!0;this.setContent(a,a.opts.errorTpl)},showLoading:function(a){(a=a||this.current)&&!a.$spinner&&(a.$spinner=e(this.opts.spinnerTpl).appendTo(a.$slide))},hideLoading:function(a){(a=a||this.current)&&a.$spinner&&(a.$spinner.remove(),delete a.$spinner)},afterMove:function(){var a=this,b=a.current,c={};b&&(b.$slide.siblings().trigger("onReset"),
e.each(a.slides,function(g,f){f.pos>=a.currPos-1&&f.pos<=a.currPos+1?c[f.pos]=f:f&&f.$slide.remove()}),a.slides=c,a.trigger("afterMove"),b.isLoaded&&a.complete())},afterLoad:function(a){this.isClosing||(a.isLoading=!1,a.isLoaded=!0,this.trigger("afterLoad",a),this.hideLoading(a),a.$ghost||this.updateSlide(a,!0),a.index===this.currIndex&&a.isMoved?this.complete():a.$ghost||this.revealImage(a))},complete:function(){var a=this,b=a.current;a.revealImage(b,function(){b.isComplete=!0;b.$slide.addClass("fancybox-slide--complete");
a.updateCursor();a.trigger("onComplete");b.opts.focus&&"image"!==b.type&&"iframe"!==b.type&&a.focus()})},preload:function(){if(!(2>this.group.length)){var a=this.slides[this.currPos+1];var b=this.slides[this.currPos-1];a&&"image"===a.type&&this.loadSlide(a);b&&"image"===b.type&&this.loadSlide(b)}},focus:function(){var a=this.current;var b=a&&a.isComplete?a.$slide.find('button,:input,[tabindex],a:not(".disabled")').filter(":visible:first"):null;b&&b.length||(b=this.$refs.container);b.focus();this.$refs.slider_wrap.scrollLeft(0);
a&&a.$slide.scrollTop(0)},activate:function(){var a=this;e(".fancybox-container").each(function(){var b=e(this).data("FancyBox");b&&b.uid!==a.uid&&!b.isClosing&&b.trigger("onDeactivate")});a.current&&(0<a.$refs.container.index()&&a.$refs.container.prependTo(r.body),a.updateControls());a.trigger("onActivate");a.addEvents()},close:function(a){var b=this,c=b.current,g=c.opts.speed,f=e.proxy(function(){b.cleanUp(a)},this);if(b.isAnimating||b.isClosing)return!1;!1===b.trigger("beforeClose",a)?(e.fancybox.stop(b.$refs.slider),
h(function(){b.update(!0,!0,150)})):(b.isClosing=!0,c.timouts&&clearTimeout(c.timouts),!0!==a&&e.fancybox.stop(b.$refs.slider),b.$refs.container.removeClass("fancybox-container--active").addClass("fancybox-container--closing"),c.$slide.removeClass("fancybox-slide--complete").siblings().remove(),c.isMoved||c.$slide.css("overflow","visible"),b.removeEvents(),b.hideLoading(c),b.hideControls(),b.updateCursor(),b.$refs.bg.css("transition-duration",g+"ms"),this.$refs.container.removeClass("fancybox-container--ready"),
!0===a?setTimeout(f,g):b.zoomInOut("Out",g,f)||e.fancybox.animate(b.$refs.container,null,{opacity:0},g,"easeInSine",f))},cleanUp:function(a){this.$refs.slider.children().trigger("onReset");this.$refs.container.empty().remove();this.trigger("afterClose",a);this.current=null;(a=e.fancybox.getInstance())?a.activate():(e("html").removeClass("fancybox-enabled"),e("body").removeAttr("style"),w.scrollTop(this.scrollTop).scrollLeft(this.scrollLeft),e("#fancybox-noscroll").remove());this.$lastFocus&&this.$lastFocus.focus()},
trigger:function(a,b){var c=Array.prototype.slice.call(arguments,1),g=b&&b.opts?b:this.current,f;g?c.unshift(g):g=this;c.unshift(this);e.isFunction(g.opts[a])&&(f=g.opts[a].apply(g,c));if(!1===f)return f;"afterClose"===a?e(r).trigger(a+".fb",c):this.$refs.container.trigger(a+".fb",c)},toggleControls:function(a){this.isHiddenControls?this.updateControls(a):this.hideControls()},hideControls:function(){this.isHiddenControls=!0;this.$refs.container.removeClass("fancybox-show-controls");this.$refs.container.removeClass("fancybox-show-caption")},
updateControls:function(a){var b=this.$refs.container,c=this.$refs.caption,g=this.current,f=g.index,l=g.opts,v=l.caption;this.isHiddenControls&&!0!==a||(this.isHiddenControls=!1,b.addClass("fancybox-show-controls").toggleClass("fancybox-show-infobar",!!l.infobar&&1<this.group.length).toggleClass("fancybox-show-buttons",!!l.buttons).toggleClass("fancybox-is-modal",!!l.modal),e(".fancybox-button--left",b).toggleClass("fancybox-button--disabled",!l.loop&&0>=f),e(".fancybox-button--right",b).toggleClass("fancybox-button--disabled",
!l.loop&&f>=this.group.length-1),e(".fancybox-button--play",b).toggle(!!(l.slideShow&&1<this.group.length)),e(".fancybox-button--close",b).toggle(!!l.closeBtn),e(".js-fancybox-count",b).html(this.group.length),e(".js-fancybox-index",b).html(f+1),g.$slide.trigger("refresh"),c&&c.empty(),v&&v.length?(c.html(v),this.$refs.container.addClass("fancybox-show-caption "),this.$caption=c):this.$refs.container.removeClass("fancybox-show-caption"))}});e.fancybox={version:"3.0.47",defaults:u,getInstance:function(a){var b=
e('.fancybox-container:not(".fancybox-container--closing"):first').data("FancyBox"),c=Array.prototype.slice.call(arguments,1);return b instanceof x?("string"===e.type(a)?b[a].apply(b,c):"function"===e.type(a)&&a.apply(b,c),b):!1},open:function(a,b,c){return new x(a,b,c)},close:function(a){var b=this.getInstance();b&&(b.close(),!0===a&&this.close())},isTouch:r.createTouch!==k&&/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent),use3d:function(){var a=r.createElement("div");return m.getComputedStyle(a).getPropertyValue("transform")&&
!(r.documentMode&&11>=r.documentMode)}(),getTranslate:function(a){var b;if(!a||!a.length)return!1;var c=a.get(0).getBoundingClientRect();(b=a.eq(0).css("transform"))&&-1!==b.indexOf("matrix")?(b=b.split("(")[1],b=b.split(")")[0],b=b.split(",")):b=[];b.length?(b=10<b.length?[b[13],b[12],b[0],b[5]]:[b[5],b[4],b[0],b[3]],b=b.map(parseFloat)):b=[0,0,1,1];return{top:b[0],left:b[1],scaleX:b[2],scaleY:b[3],opacity:parseFloat(a.css("opacity")),width:c.width,height:c.height}},setTranslate:function(a,b){var c=
"",g={};if(a&&b){if(b.left!==k||b.top!==k)c=(b.left===k?a.position().top:b.left)+"px, "+(b.top===k?a.position().top:b.top)+"px",c=this.use3d?"translate3d("+c+", 0px)":"translate("+c+")";b.scaleX!==k&&b.scaleY!==k&&(c=(c.length?c+" ":"")+"scale("+b.scaleX+", "+b.scaleY+")");c.length&&(g.transform=c);b.opacity!==k&&(g.opacity=b.opacity);b.width!==k&&(g.width=b.width);b.height!==k&&(g.height=b.height);return a.css(g)}},easing:{easeOutCubic:function(a,b,c,g){return c*((a=a/g-1)*a*a+1)+b},easeInCubic:function(a,
b,c,g){return c*(a/=g)*a*a+b},easeOutSine:function(a,b,c,g){return c*Math.sin(a/g*(Math.PI/2))+b},easeInSine:function(a,b,c,g){return-c*Math.cos(a/g*(Math.PI/2))+c+b}},stop:function(a){a.removeData("animateID")},animate:function(a,b,c,g,f,l){var v=this,t=null,y=0,z,A,C,D=function(){c.scaleX!==k&&c.scaleY!==k&&b&&b.width!==k&&b.height!==k&&(c.width=b.width*c.scaleX,c.height=b.height*c.scaleY,c.scaleX=1,c.scaleY=1);v.setTranslate(a,c);l()},E=function(B){z=[];A=0;if(a.length&&a.data("animateID")===C)if(B=
B||Date.now(),t&&(A=B-t),t=B,y+=A,y>=g)D();else{for(var F in c)c.hasOwnProperty(F)&&b[F]!==k&&(z[F]=b[F]==c[F]?c[F]:v.easing[f](y,b[F],c[F]-b[F],g));v.setTranslate(a,z);h(E)}};v.animateID=C=v.animateID===k?1:v.animateID+1;a.data("animateID",C);l===k&&"function"==e.type(f)&&(l=f,f=k);f||(f="easeOutCubic");l=l||e.noop;b?this.setTranslate(a,b):b=this.getTranslate(a);g?(a.show(),h(E)):D()}};e.fn.fancybox=function(a){this.off("click.fb-start").on("click.fb-start",{items:this,options:a||{}},q);return this};
e(r).on("click.fb-start","[data-fancybox]",q)})(window,document,window.jQuery);
(function(m){var r=function(k,q,u){if(k)return u=u||"","object"===m.type(u)&&(u=m.param(u,!0)),m.each(q,function(w,n){k=k.replace("$"+w,n||"")}),u.length&&(k+=(0<k.indexOf("?")?"&":"?")+u),k},e={youtube:{matcher:/(youtube\.com|youtu\.be|youtube\-nocookie\.com)\/(watch\?(.*&)?v=|v\/|u\/|embed\/?)?(videoseries\?list=(.*)|[\w-]{11}|\?listType=(.*)&list=(.*))(.*)/i,params:{autoplay:1,autohide:1,fs:1,rel:0,hd:1,wmode:"transparent",enablejsapi:1,html5:1},paramPlace:8,type:"iframe",url:"//www.youtube.com/embed/$4",
thumb:"//img.youtube.com/vi/$4/hqdefault.jpg"},vimeo:{matcher:/^.+vimeo.com\/(.*\/)?([\d]+)(.*)?/,params:{autoplay:1,hd:1,show_title:1,show_byline:1,show_portrait:0,fullscreen:1,api:1},paramPlace:3,type:"iframe",url:"//player.vimeo.com/video/$2"},metacafe:{matcher:/metacafe.com\/watch\/(\d+)\/(.*)?/,type:"iframe",url:"//www.metacafe.com/embed/$1/?ap=1"},dailymotion:{matcher:/dailymotion.com\/video\/(.*)\/?(.*)/,params:{additionalInfos:0,autoStart:1},type:"iframe",url:"//www.dailymotion.com/embed/video/$1"},
vine:{matcher:/vine.co\/v\/([a-zA-Z0-9\?=\-]+)/,type:"iframe",url:"//vine.co/v/$1/embed/simple"},instagram:{matcher:/(instagr\.am|instagram\.com)\/p\/([a-zA-Z0-9_\-]+)\/?/i,type:"image",url:"//$1/p/$2/media/?size=l"},google_maps:{matcher:/(maps\.)?google\.([a-z]{2,3}(\.[a-z]{2})?)\/(((maps\/(place\/(.*)\/)?@(.*),(\d+.?\d+?)z))|(\?ll=))(.*)?/i,type:"iframe",url:function(k){return"//maps.google."+k[2]+"/?ll="+(k[9]?k[9]+"&z="+Math.floor(k[10])+(k[12]?k[12].replace(/^\//,"&"):""):k[12])+"&output="+(k[12]&&
0<k[12].indexOf("layer=c")?"svembed":"embed")}}};m(document).on("onInit.fb",function(k,q){m.each(q.group,function(u,w){var n=w.src||"",d=!1,h,p,x,a,b,c;w.type||(m.each(e,function(g,f){p=n.match(f.matcher);b={};c=g;if(p){d=f.type;if(f.paramPlace&&p[f.paramPlace]){a=p[f.paramPlace];"?"==a[0]&&(a=a.substring(1));a=a.split("&");for(var l=0;l<a.length;++l){var v=a[l].split("=",2);2==v.length&&(b[v[0]]=decodeURIComponent(v[1].replace(/\+/g," ")))}}x=m.extend(!0,{},f.params,w.opts[g],b);n="function"===m.type(f.url)?
f.url.call(this,p,x,w):r(f.url,p,x);h="function"===m.type(f.thumb)?f.thumb.call(this,p,x,w):r(f.thumb,p);"vimeo"===c&&(n=n.replace("&%23","#"));return!1}}),d?(w.src=n,w.type=d,w.opts.thumb||w.opts.$thumb&&w.opts.$thumb.length||(w.opts.thumb=h),"iframe"===d&&(m.extend(!0,w.opts,{iframe:{preload:!1,scrolling:"no"},smallBtn:!1,closeBtn:!0,fullScreen:!1,slideShow:!1}),w.opts.slideClass+=" fancybox-slide--video")):w.type="iframe")})})})(window.jQuery);
(function(m,r,e){var k=function(){return m.requestAnimationFrame||m.webkitRequestAnimationFrame||m.mozRequestAnimationFrame||function(d){m.setTimeout(d,1E3/60)}}(),q=function(d){var h=[];d=d.originalEvent||d||m.e;d=d.touches&&d.touches.length?d.touches:d.changedTouches&&d.changedTouches.length?d.changedTouches:[d];for(var p in d)d[p].pageX?h.push({x:d[p].pageX,y:d[p].pageY}):d[p].clientX&&h.push({x:d[p].clientX,y:d[p].clientY});return h},u=function(d,h,p){return h&&d?"x"===p?d.x-h.x:"y"===p?d.y-h.y:
Math.sqrt(Math.pow(d.x-h.x,2)+Math.pow(d.y-h.y,2)):0},w=function(d){return d.is("a")||d.is("button")||d.is("input")||d.is("select")||d.is("textarea")||e.isFunction(d.get(0).onclick)},n=function(d){this.instance=d;this.$wrap=d.$refs.slider_wrap;this.$slider=d.$refs.slider;this.$container=d.$refs.container;this.destroy();this.$wrap.on("touchstart.fb mousedown.fb",e.proxy(this,"ontouchstart"))};n.prototype.destroy=function(){this.$wrap.off("touchstart.fb mousedown.fb touchmove.fb mousemove.fb touchend.fb touchcancel.fb mouseup.fb mouseleave.fb")};
n.prototype.ontouchstart=function(d){var h=e(d.target),p=this.instance.current,x=p.$content||p.$placeholder;this.startPoints=q(d);this.$target=h;this.$content=x;this.canvasWidth=Math.round(p.$slide[0].clientWidth);this.canvasHeight=Math.round(p.$slide[0].clientHeight);this.startEvent=d;if(d.originalEvent.clientX>this.canvasWidth+p.$slide.offset().left)return!0;if(!(x=w(h)||w(h.parent())))for(;;){x=h.get(0);var a=m.getComputedStyle(x)["overflow-y"],b=m.getComputedStyle(x)["overflow-x"];b=("scroll"===
b||"auto"===b)&&x.scrollWidth>x.clientWidth;if(x=("scroll"===a||"auto"===a)&&x.scrollHeight>x.clientHeight||b)break;h=h.parent();if(!h.length||h.hasClass("fancybox-slider")||h.is("body"))break}if(!x){if(!p.opts.touch)return this.endPoints=this.startPoints,this.ontap();d.originalEvent&&2==d.originalEvent.button||(d.stopPropagation(),d.preventDefault(),!p||this.instance.isAnimating||this.instance.isClosing||!this.startPoints||1<this.startPoints.length&&!p.isMoved||(this.$wrap.off("touchmove.fb mousemove.fb",
e.proxy(this,"ontouchmove")),this.$wrap.off("touchend.fb touchcancel.fb mouseup.fb mouseleave.fb",e.proxy(this,"ontouchend")),this.$wrap.on("touchend.fb touchcancel.fb mouseup.fb mouseleave.fb",e.proxy(this,"ontouchend")),this.$wrap.on("touchmove.fb mousemove.fb",e.proxy(this,"ontouchmove")),this.startTime=(new Date).getTime(),this.distanceX=this.distanceY=this.distance=0,this.isZooming=this.isSwiping=this.isPanning=this.canTap=!1,this.sliderStartPos=e.fancybox.getTranslate(this.$slider),this.contentStartPos=
e.fancybox.getTranslate(this.$content),this.contentLastPos=null,1!==this.startPoints.length||this.isZooming||(this.canTap=p.isMoved,"image"===p.type&&(this.contentStartPos.width>this.canvasWidth+1||this.contentStartPos.height>this.canvasHeight+1)?(e.fancybox.stop(this.$content),this.isPanning=!0):(e.fancybox.stop(this.$slider),this.isSwiping=!0),this.$container.addClass("fancybox-controls--isGrabbing")),2===this.startPoints.length&&p.isMoved&&!p.hasError&&"image"===p.type&&(p.isLoaded||p.$ghost)&&
(this.isZooming=!0,this.isPanning=this.isSwiping=!1,e.fancybox.stop(this.$content),this.centerPointStartX=.5*(this.startPoints[0].x+this.startPoints[1].x)-e(m).scrollLeft(),this.centerPointStartY=.5*(this.startPoints[0].y+this.startPoints[1].y)-e(m).scrollTop(),this.percentageOfImageAtPinchPointX=(this.centerPointStartX-this.contentStartPos.left)/this.contentStartPos.width,this.percentageOfImageAtPinchPointY=(this.centerPointStartY-this.contentStartPos.top)/this.contentStartPos.height,this.startDistanceBetweenFingers=
u(this.startPoints[0],this.startPoints[1]))))}};n.prototype.ontouchmove=function(d){d.preventDefault();if((this.newPoints=q(d))&&this.newPoints.length&&(this.distanceX=u(this.newPoints[0],this.startPoints[0],"x"),this.distanceY=u(this.newPoints[0],this.startPoints[0],"y"),this.distance=u(this.newPoints[0],this.startPoints[0]),0<this.distance))if(this.isSwiping)this.onSwipe();else if(this.isPanning)this.onPan();else if(this.isZooming)this.onZoom()};n.prototype.onSwipe=function(){var d=this,h=d.isSwiping,
p=d.sliderStartPos.left;!0===h?10<Math.abs(d.distance)&&(2>d.instance.group.length?d.isSwiping="y":!d.instance.current.isMoved||!1===d.instance.opts.touch.vertical||"auto"===d.instance.opts.touch.vertical&&800<e(m).width()?d.isSwiping="x":(h=Math.abs(180*Math.atan2(d.distanceY,d.distanceX)/Math.PI),d.isSwiping=45<h&&135>h?"y":"x"),d.canTap=!1,d.instance.current.isMoved=!1,d.startPoints=d.newPoints):("x"==h&&(p=!d.instance.current.opts.loop&&0===d.instance.current.index&&0<d.distanceX?p+Math.pow(d.distanceX,
.8):!d.instance.current.opts.loop&&d.instance.current.index===d.instance.group.length-1&&0>d.distanceX?p-Math.pow(-d.distanceX,.8):p+d.distanceX),d.sliderLastPos={top:"x"==h?0:d.sliderStartPos.top+d.distanceY,left:p},k(function(){e.fancybox.setTranslate(d.$slider,d.sliderLastPos)}))};n.prototype.onPan=function(){var d=this;d.canTap=!1;var h=d.limitMovement(d.contentStartPos.width>d.canvasWidth?d.contentStartPos.left+d.distanceX:d.contentStartPos.left,d.contentStartPos.top+d.distanceY,d.contentStartPos.width,
d.contentStartPos.height);h.scaleX=d.contentStartPos.scaleX;h.scaleY=d.contentStartPos.scaleY;d.contentLastPos=h;k(function(){e.fancybox.setTranslate(d.$content,d.contentLastPos)})};n.prototype.limitMovement=function(d,h,p,x){var a=this.canvasWidth,b=this.canvasHeight,c=this.contentStartPos.left,g=this.contentStartPos.top,f=this.distanceX,l=this.distanceY;var v=Math.max(0,.5*a-.5*p);var t=Math.max(0,.5*b-.5*x);var y=Math.min(a-p,.5*a-.5*p);var z=Math.min(b-x,.5*b-.5*x);p>a&&(0<f&&d>v&&(d=v-1+Math.pow(-v+
c+f,.8)||0),0>f&&d<y&&(d=y+1-Math.pow(y-c-f,.8)||0));x>b&&(0<l&&h>t&&(h=t-1+Math.pow(-t+g+l,.8)||0),0>l&&h<z&&(h=z+1-Math.pow(z-g-l,.8)||0));return{top:h,left:d}};n.prototype.limitPosition=function(d,h,p,x){var a=this.canvasWidth,b=this.canvasHeight;p>a?(d=0<d?0:d,d=d<a-p?a-p:d):d=Math.max(0,a/2-p/2);x>b?(h=0<h?0:h,h=h<b-x?b-x:h):h=Math.max(0,b/2-x/2);return{top:h,left:d}};n.prototype.onZoom=function(){var d=this,h=d.contentStartPos.width,p=d.contentStartPos.height,x=d.contentStartPos.left,a=d.contentStartPos.top,
b=u(d.newPoints[0],d.newPoints[1])/d.startDistanceBetweenFingers,c=Math.floor(h*b),g=Math.floor(p*b);h=(h-c)*d.percentageOfImageAtPinchPointX;p=(p-g)*d.percentageOfImageAtPinchPointY;var f=(d.newPoints[0].x+d.newPoints[1].x)/2-e(m).scrollLeft(),l=(d.newPoints[0].y+d.newPoints[1].y)/2-e(m).scrollTop();x={top:a+(p+(l-d.centerPointStartY)),left:x+(h+(f-d.centerPointStartX)),scaleX:d.contentStartPos.scaleX*b,scaleY:d.contentStartPos.scaleY*b};d.canTap=!1;d.newWidth=c;d.newHeight=g;d.contentLastPos=x;
k(function(){e.fancybox.setTranslate(d.$content,d.contentLastPos)})};n.prototype.ontouchend=function(d){var h=this.instance.current,p=Math.max((new Date).getTime()-this.startTime,1),x=this.isSwiping,a=this.isPanning,b=this.isZooming;this.endPoints=q(d);this.$container.removeClass("fancybox-controls--isGrabbing");this.$wrap.off("touchmove.fb mousemove.fb",e.proxy(this,"ontouchmove"));this.$wrap.off("touchend.fb touchcancel.fb mouseup.fb mouseleave.fb",e.proxy(this,"ontouchend"));this.isZooming=this.isPanning=
this.isSwiping=!1;if(this.canTap)return this.ontap();this.velocityX=this.distanceX/p*.5;this.velocityY=this.distanceY/p*.5;this.speed=h.opts.speed||330;this.speedX=Math.max(.75*this.speed,Math.min(1.5*this.speed,1/Math.abs(this.velocityX)*this.speed));this.speedY=Math.max(.75*this.speed,Math.min(1.5*this.speed,1/Math.abs(this.velocityY)*this.speed));a?this.endPanning():b?this.endZooming():this.endSwiping(x)};n.prototype.endSwiping=function(d){"y"==d&&50<Math.abs(this.distanceY)?(e.fancybox.animate(this.$slider,
null,{top:this.sliderStartPos.top+this.distanceY+150*this.velocityY,left:this.sliderStartPos.left,opacity:0},this.speedY),this.instance.close(!0)):"x"==d&&50<this.distanceX?this.instance.previous(this.speedX):"x"==d&&-50>this.distanceX?this.instance.next(this.speedX):this.instance.update(!1,!0,150)};n.prototype.endPanning=function(){if(this.contentLastPos){var d=this.contentLastPos.left+this.velocityX*this.speed*2;d=this.limitPosition(d,this.contentLastPos.top+this.velocityY*this.speed*2,this.contentStartPos.width,
this.contentStartPos.height);d.width=this.contentStartPos.width;d.height=this.contentStartPos.height;e.fancybox.animate(this.$content,null,d,this.speed,"easeOutSine")}};n.prototype.endZooming=function(){var d=this.instance.current,h=this.newWidth,p=this.newHeight;if(this.contentLastPos){var x=this.contentLastPos.left;var a=this.contentLastPos.top;e.fancybox.setTranslate(this.$content,{top:a,left:x,width:h,height:p,scaleX:1,scaleY:1});h<this.canvasWidth&&p<this.canvasHeight?this.instance.scaleToFit(150):
h>d.width||p>d.height?this.instance.scaleToActual(this.centerPointStartX,this.centerPointStartY,150):(d=this.limitPosition(x,a,h,p),e.fancybox.animate(this.$content,null,d,this.speed,"easeOutSine"))}};n.prototype.ontap=function(){var d=this,h=d.instance,p=h.current,x=d.endPoints[0].x,a=d.endPoints[0].y;x-=d.$wrap.offset().left;a-=d.$wrap.offset().top;h.SlideShow&&h.SlideShow.isActive&&h.SlideShow.stop();if(e.fancybox.isTouch){if(d.tapped){clearTimeout(d.tapped);d.tapped=null;if(50<Math.abs(x-d.x)||
50<Math.abs(a-d.y)||!p.isMoved)return this;"image"==p.type&&(p.isLoaded||p.$ghost)&&(h.canPan()?h.scaleToFit():h.isScaledDown()&&h.scaleToActual(x,a))}else d.x=x,d.y=a,d.tapped=setTimeout(function(){d.tapped=null;h.toggleControls(!0)},300);return this}p.opts.closeClickOutside&&d.$target.is(".fancybox-slide")?h.close(d.startEvent):"image"==p.type&&p.isMoved&&(h.canPan()?h.scaleToFit():h.isScaledDown()?h.scaleToActual(x,a):2>h.group.length&&h.close(d.startEvent))};e(r).on("onActivate.fb",function(d,
h){h&&!h.Guestures&&(h.Guestures=new n(h))});e(r).on("beforeClose.fb",function(d,h){h&&h.Guestures&&h.Guestures.destroy()})})(window,document,window.jQuery);
(function(m,r){var e=function(k){this.instance=k;this.init()};r.extend(e.prototype,{timer:null,isActive:!1,$button:null,speed:3E3,init:function(){var k=this;k.$button=r('<button data-fancybox-play class="fancybox-button fancybox-button--play" title="Slideshow (P)"></button>').appendTo(k.instance.$refs.buttons);k.instance.$refs.container.on("click","[data-fancybox-play]",function(){k.toggle()})},set:function(){var k=this;k.instance&&k.instance.current&&(k.instance.current.opts.loop||k.instance.currIndex<
k.instance.group.length-1)?k.timer=setTimeout(function(){k.instance.next()},k.instance.current.opts.slideShow.speed||k.speed):k.stop()},clear:function(){clearTimeout(this.timer);this.timer=null},start:function(){this.stop();this.instance&&this.instance.current&&(this.instance.current.opts.loop||this.instance.currIndex<this.instance.group.length-1)&&(this.instance.$refs.container.on({"beforeLoad.fb.player":r.proxy(this,"clear"),"onComplete.fb.player":r.proxy(this,"set")}),this.isActive=!0,this.instance.current.isComplete&&
this.set(),this.instance.$refs.container.trigger("onPlayStart"),this.$button.addClass("fancybox-button--pause"))},stop:function(){this.clear();this.instance.$refs.container.trigger("onPlayEnd").off(".player");this.$button.removeClass("fancybox-button--pause");this.isActive=!1},toggle:function(){this.isActive?this.stop():this.start()}});r(m).on("onInit.fb",function(k,q){q&&1<q.group.length&&q.opts.slideShow&&!q.SlideShow&&(q.SlideShow=new e(q))});r(m).on("beforeClose.fb onDeactivate.fb",function(k,
q){q&&q.SlideShow&&q.SlideShow.stop()})})(document,window.jQuery);
(function(m,r){var e=function(){var q=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),
"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],u,w={},n;for(n=0;n<q.length;n++)if((u=q[n])&&u[1]in m){for(n=0;n<u.length;n++)w[q[0][n]]=u[n];return w}return!1}();if(e){var k={request:function(q){q=q||m.documentElement;q[e.requestFullscreen](q.ALLOW_KEYBOARD_INPUT)},exit:function(){m[e.exitFullscreen]()},toggle:function(q){this.isFullscreen()?this.exit():this.request(q)},isFullscreen:function(){return!!m[e.fullscreenElement]},
enabled:function(){return!!m[e.fullscreenEnabled]}};r(m).on({"onInit.fb":function(q,u){if(u&&u.opts.fullScreen&&!u.FullScreen){var w=u.$refs.container;u.$refs.button_fs=r('<button data-fancybox-fullscreen class="fancybox-button fancybox-button--fullscreen" title="Full screen (F)"></button>').appendTo(u.$refs.buttons);w.on("click.fb-fullscreen","[data-fancybox-fullscreen]",function(n){n.stopPropagation();n.preventDefault();k.toggle(w[0])});!0===u.opts.fullScreen.requestOnStart&&k.request(w[0])}},"beforeMove.fb":function(q,
u){u&&u.$refs.button_fs&&u.$refs.button_fs.toggle(!!u.current.opts.fullScreen)},"beforeClose.fb":function(){k.exit()}});r(m).on(e.fullscreenchange,function(){var q=r.fancybox.getInstance(),u=q?q.current.$placeholder:null;u&&(u.css("transition","none"),q.isAnimating=!1,q.update(!0,!0,0))})}})(document,window.jQuery);
(function(m,r){var e=function(k){this.instance=k;this.init()};r.extend(e.prototype,{$button:null,$grid:null,$list:null,isVisible:!1,init:function(){var k=this;k.$button=r('<button data-fancybox-thumbs class="fancybox-button fancybox-button--thumbs" title="Thumbnails (G)"></button>').appendTo(this.instance.$refs.buttons).on("touchend click",function(q){q.stopPropagation();q.preventDefault();k.toggle()})},create:function(){var k=this.instance,q;this.$grid=r('<div class="fancybox-thumbs"></div>').appendTo(k.$refs.container);
var u="<ul>";r.each(k.group,function(w,n){q=n.opts.thumb||(n.opts.$thumb?n.opts.$thumb.attr("src"):null);q||"image"!==n.type||(q=n.src);q&&q.length&&(u+='<li data-index="'+w+'"  tabindex="0" class="fancybox-thumbs-loading"><img data-src="'+q+'" /></li>')});u+="</ul>";this.$list=r(u).appendTo(this.$grid).on("click touchstart","li",function(){k.jumpTo(r(this).data("index"))});this.$list.find("img").hide().one("load",function(){var w=r(this).parent().removeClass("fancybox-thumbs-loading"),n=w.outerWidth();
w=w.outerHeight();var d=this.naturalWidth||this.width;var h=this.naturalHeight||this.height;var p=d/n;var x=h/w;1<=p&&1<=x&&(p>x?(d/=x,h=w):(d=n,h/=p));r(this).css({width:Math.floor(d),height:Math.floor(h),"margin-top":Math.min(0,Math.floor(.3*w-.3*h)),"margin-left":Math.min(0,Math.floor(.5*n-.5*d))}).show()}).each(function(){this.src=r(this).data("src")})},focus:function(){this.instance.current&&this.$list.children().removeClass("fancybox-thumbs-active").filter('[data-index="'+this.instance.current.index+
'"]').addClass("fancybox-thumbs-active").focus()},close:function(){this.$grid.hide()},update:function(){this.instance.$refs.container.toggleClass("fancybox-container--thumbs",this.isVisible);this.isVisible?(this.$grid||this.create(),this.$grid.show(),this.focus()):this.$grid&&this.$grid.hide();this.instance.update()},hide:function(){this.isVisible=!1;this.update()},show:function(){this.isVisible=!0;this.update()},toggle:function(){this.isVisible?this.hide():this.show()}});r(m).on("onInit.fb",function(k,
q){k=q.group[0];var u=q.group[1];q.opts.thumbs&&!q.Thumbs&&1<q.group.length&&("image"==k.type||k.opts.thumb||k.opts.$thumb)&&("image"==u.type||u.opts.thumb||u.opts.$thumb)&&(q.Thumbs=new e(q))});r(m).on("beforeMove.fb",function(k,q,u){if(k=q&&q.Thumbs)u.modal?(k.$button.hide(),k.hide()):(!0===q.opts.thumbs.showOnStart&&q.firstRun&&k.show(),k.$button.show(),k.isVisible&&k.focus())});r(m).on("beforeClose.fb",function(k,q){q&&q.Thumbs&&(q.Thumbs.isVisible&&!1!==q.opts.thumbs.hideOnClosing&&q.Thumbs.close(),
q.Thumbs=null)})})(document,window.jQuery);
(function(m,r,e){function k(){var n=r.location.hash.substr(1),d=n.split("-"),h=1<d.length&&/^\+?\d+$/.test(d[d.length-1])?parseInt(d.pop(-1),10)||1:1;d=d.join("-");1>h&&(h=1);return{hash:n,index:h,gallery:d}}function q(n){if(""!==n.gallery){var d=e("[data-fancybox='"+e.escapeSelector(n.gallery)+"']").eq(n.index-1);d.length?d.trigger("click"):e("#"+e.escapeSelector(n.gallery)).trigger("click")}}function u(n){if(!n)return!1;n=n.current?n.current.opts:n.opts;return n.$orig?n.$orig.data("fancybox"):n.hash||
""}e.escapeSelector||(e.escapeSelector=function(n){return(n+"").replace(/([\0-\x1f\x7f]|^-?\d)|^-$|[^\x80-\uFFFF\w-]/g,function(d,h){return h?"\x00"===d?"\ufffd":d.slice(0,-1)+"\\"+d.charCodeAt(d.length-1).toString(16)+" ":"\\"+d})});var w=null;e(function(){setTimeout(function(){!1!==e.fancybox.defaults.hash&&(e(r).on("hashchange.fb",function(){var n=k();e.fancybox.getInstance()?w&&w!==n.gallery+"-"+n.index&&(w=null,e.fancybox.close()):""!==n.gallery&&q(n)}),e(m).on({"onInit.fb":function(n,d){n=k();
var h=u(d);h&&n.gallery&&h==n.gallery&&(d.currIndex=n.index-1)},"beforeMove.fb":function(n,d,h){(n=u(d))&&""!==n&&(0>r.location.hash.indexOf(n)&&(d.opts.origHash=r.location.hash),w=n+(1<d.group.length?"-"+(h.index+1):""),"pushState"in history?history.pushState("",m.title,r.location.pathname+r.location.search+"#"+w):r.location.hash=w)},"beforeClose.fb":function(n,d,h){n=u(d);d=d&&d.opts.origHash?d.opts.origHash:"";n&&""!==n&&("pushState"in history?history.pushState("",m.title,r.location.pathname+r.location.search+
d):r.location.hash=d);w=null}}),q(k()))},50)})})(document,window,window.jQuery);process=process||{env:{NODE_ENV:"development"}};
jQuery(document).ready(function(m){m(".material-content img").not(".directLink").each(function(){m(this).parents("ins").eq(0).length||(m(this).parents("a").eq(0).length?0<m.url(m(this).parents("a").attr("href")).attr("host").search(/overclockers\.ru/i)?m(this).parents("a").attr("data-fancybox","gallery"):m(this).parents("a").attr("target","_blank"):m(this).wrap(m("<a></a>").attr("href",m(this).attr("data-src")).attr("data-fancybox","gallery")))});m(".image-view").attr("data-fancybox","gallery");m(".startFancybox").click(function(r){r.preventDefault();
m("a[data-fancybox^='gallery']:first").click()});m.fancybox.defaults.hash=!1});process=process||{env:{NODE_ENV:"development"}};
$(function(){"undefined"!==typeof currentMaterialId&&$(".material-near-feed .material-id-"+currentMaterialId).addClass("current");$(".comments-show").on("click",function(){$(".comments-show").hide();$(".comments-hide").show();$(".comments-wrap").show()});$(".comments-hide").on("click",function(){$(".comments-hide").hide();$(".comments-wrap").hide();$(".comments-show").show()});$(".difference-tab").tab();$(".paging-top-link").on("click",function(m){m.preventDefault();$("#pagingOnTop").toggle()});$(".spoiler-title").append('<span class="spoiler-help">(\u043a\u043b\u0438\u043a\u043d\u0438\u0442\u0435, \u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u0440\u044b\u0442\u044c)</span>');
$(".spoiler-block .spoiler-title").on("click",function(){$(this).children(".spoiler-icon").hasClass("fa-plus-square")?($(this).children(".spoiler-icon").removeClass("fa-plus-square"),$(this).children(".spoiler-icon").addClass("fa-minus-square"),$(this).children(".spoiler-help").text("(\u043a\u043b\u0438\u043a\u043d\u0438\u0442\u0435, \u0447\u0442\u043e\u0431\u044b \u0437\u0430\u043a\u0440\u044b\u0442\u044c)"),$(this).parent(".spoiler-block").children(".spoiler-body").show(),bLazy.load($(".spoiler-block .spoiler-body img"),
!0)):($(this).children(".spoiler-icon").removeClass("fa-minus-square"),$(this).children(".spoiler-icon").addClass("fa-plus-square"),$(this).children(".spoiler-help").text("(\u043a\u043b\u0438\u043a\u043d\u0438\u0442\u0435, \u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u0440\u044b\u0442\u044c)"),$(this).parent(".spoiler-block").children(".spoiler-body").hide())});$(".spoiler-block-2 .spoiler-title").on("click",function(){1==$(this).data("close")?($(this).children(".spoiler-icon").removeClass("plus square"),
$(this).children(".spoiler-icon").addClass("minus square"),$(this).children(".spoiler-help").text("(\u043a\u043b\u0438\u043a\u043d\u0438\u0442\u0435, \u0447\u0442\u043e\u0431\u044b \u0437\u0430\u043a\u0440\u044b\u0442\u044c)"),$(this).parent(".spoiler-block-2").children(".spoiler-body").show(),bLazy.load($(".spoiler-block-2 .spoiler-body img"),!0),$(this).data("close",0)):($(this).children(".spoiler-icon").removeClass("minus square"),$(this).children(".spoiler-icon").addClass("plus square"),$(this).children(".spoiler-help").text("(\u043a\u043b\u0438\u043a\u043d\u0438\u0442\u0435, \u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043a\u0440\u044b\u0442\u044c)"),
$(this).parent(".spoiler-block-2").children(".spoiler-body").hide(),$(this).data("close",1))})});process=process||{env:{NODE_ENV:"development"}};
function bookmarkInit(){$(".control-bookmark-link").api({action:"controlBookmark",method:"POST",dataType:"json",beforeSend:function(m){m.data=$.extend(m.data,{addAction:$(this).data("add"),forWhat:$(this).data("for-what"),whatId:$(this).data("what-id")});return m},onRequest:function(m,r){$(".control-bookmark-link").find(".control-icon").removeClass("bookmark bookmark outline red");$(".control-bookmark-link").find(".control-icon").addClass("asterisk loading")},onComplete:function(m,r,e){$(".control-bookmark-link").find(".control-icon").removeClass("asterisk loading")},
onSuccess:function(m){2==$(this).data("add")?($(".control-bookmark-link").data("add",0),$(".control-bookmark-link.bookmark-label").find(".control-icon").addClass("bookmark outline"),$(".control-bookmark-link.bookmark-icon-txt").find(".control-icon").addClass("bookmark"),$(".control-bookmark-link.bookmark-icon-txt").find(".icon.label").removeClass("blue")):($(".control-bookmark-link").data("add",2),$(".control-bookmark-link.bookmark-label").find(".control-icon").addClass("bookmark red"),$(".control-bookmark-link.bookmark-icon-txt").find(".control-icon").addClass("bookmark"),
$(".control-bookmark-link.bookmark-icon-txt").find(".icon.label").addClass("blue"));$(".control-bookmark-link.bookmark-icon-txt").find(".status-text").text(m.txtLong)},onFailure:function(m){showErrorMessage(m.message)}})}jQuery(document).ready(function(m){bookmarkInit()});process=process||{env:{NODE_ENV:"development"}};
function controlViewJq(m,r,e){m=$.ajax({url:"/webservice/controlView?matId="+m+"&catId="+r+"&isBlog="+e,type:"GET",dataType:"jsonp",crossDomain:!0,contentType:"application/json",jsonp:jsonpKey,cache:!1});m.done(function(k,q,u){});m.fail(function(k,q,u){});m.always(function(){})}function controlView(m,r,e){var k=new XMLHttpRequest;k.open("GET","/webservice/controlView?matId="+m+"&catId="+r+"&isBlog="+e,!0);k.send()}process=process||{env:{NODE_ENV:"development"}};
cackle_widget=window.cackle_widget||[];
function cackleChannelInit(m,r,e,k,q,u,w){var n="";1==e&&(n=k);e=100;u&&0<u&&(e=u);cackle_widget=window.cackle_widget||[];cackle_widget.push({widget:"Comment",id:m,container:"mcContainer-"+r,channel:r,countContainer:"cackleRemoteCount-"+r,ratingOff:!0,schemaOff:!0,providers:"vkontakte;facebook;twitter;odnoklassniki;instagram;other;",ssoAuth:n,size:e,theme:w,ssoProvider:{name:"\u0412\u043e\u0439\u0442\u0438 \u0447\u0435\u0440\u0435\u0437 overclockers.ru",url:q,logo:"https://overclockers.ru/assets/logo_micro.png",
width:56,height:30}})}process=process||{env:{NODE_ENV:"development"}};